### ISSUE TITLE
Metrics Collector for TensorFlowEvent and GCS path 

### ISSUE THREAD

**Issue by martham93** [kubeflow/katib#1007]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I created a `yaml` file and included a path to where tensorflow event files are stored on Google Cloud Storage. I was wondering if it is possible for katib to handle a source file for a tf event as a metrics collector directly from GCS.  

```
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: fbeta_m
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: "gs://ffda_poi_dar_updated/model_dir_trials/{{.Trial}}/eval/"
        kind: Directory
    collector:
      kind: TensorFlowEvent
```
the command `kubectl create -f <path to yaml> fails with the following error
```
Error from server (InternalError): error when creating "/Users/marthamorrissey/repos/ffda-poi/katib/ffda_poi_experiment_20.yaml": Internal error occurred: admission webhook "mutating.experiment.katib.kubeflow.org" denied the request: v1alpha3.Experiment.Spec: v1alpha3.ExperimentSpec.MetricsCollectorSpec: v1alpha3.MetricsCollectorSpec.Source: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|"source":"gs://ffda_|..., bigger context ...|{"collector":{"kind":"TensorFlowEvent"},"source":"gs://ffda_poi_dar_updated/model_dir_trials/{{.Tria|...
```

**What did you expect to happen:**

The experiment to be created after running `kubectl create -f <path to yaml>`
`experiment.kubeflow.org/poi-experiment25 created` 

**Anything else you would like to add:**
Please let me know if I should attach my entire experiment yaml file. 

**Environment:**
- Kubeflow version: 0.7.1
