### ISSUE TITLE
Bayesianoptimization algorithm does not work when hyperparameter are negative doubles

### ISSUE THREAD

**Issue by JustinReboullot** [kubeflow/katib#1037]
/kind bug

**What steps did you take and what happened:**

Katib suggest NaN values when submitting an experiment with:
 - a parameter with `parametertype: double`
 - a feasibleSpace including negative numbers
 - bayesianoptimization as algorithm

For example this kind of yaml makes Katib suggesting NaN for the parameter `my-param`.
```
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: my-buggy-experiment
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: my_metric
  algorithm:
    algorithmName: bayesianoptimization
    algorithmSettings:
      - name: "n_initial_points"
        value: "5"
  metricsCollectorSpec:
    collector:
      kind: StdOut
  parallelTrialCount: 1
  maxTrialCount: 2
  maxFailedTrialCount: 3
  parameters:
    - name: --my-param
      parameterType: double
      feasibleSpace:
        min: "-1.0"
        max: "1.0"
trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: some_image
                  command:
                  - "python"
                  - "some_script.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
```

**What did you expect to happen:**
Katib should not suggest NaN for `my-param` but values between -1 and 1.

**Anything else you would like to add:**
Is it due to the `log-uniform` prior in https://github.com/kubeflow/katib/blob/489d52b0094e36ccb53d26cf0127add9e00bd606/pkg/suggestion/v1alpha3/skopt/base_skopt_service.py line 43?

**Environment:**

- Kubeflow version:  0.7.0
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.14.0
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3 LTS
