### ISSUE TITLE
Step field does not work with int parameters

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow/katib#1119]
/kind bug

**What steps did you take and what happened:**
I create an experiment over two integer parameters, using grid search. The template looks like this:

```yaml
apiVersion: kubeflow.org/v1alpha3
kind: Experiment
metadata:
  labels:
    controller-tools.k8s.io: '1.0'
  name: katib-test
spec:
  algorithm:
    algorithmName: grid
  objective:
    additionalMetricNames:
    goal: 100
    objectiveMetricName: result
    type: maximize
  parameters:
  - feasibleSpace:
      max: '50'
      min: '1'
      step: '10'
    name: a
    parameterType: int
  - feasibleSpace:
      max: '50'
      min: '1'
      step: '9'
    name: b
    parameterType: int
  trialTemplate:
    goTemplate:
      rawTemplate: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {{.Trial}}
          namespace: {{.NameSpace}}
        spec:
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
            spec:
              restartPolicy: Never
              containers:
                - name: {{.Trial}}
                  image: <myimage>
                  command:
                    - python3 -u -c "<some-command>"
```

The trial start as expected, but the `step` field doesn't have any effect. I see the parameters being increased by `1`, instead of `step`.

**What did you expect to happen:**
I would expect `step` to have effect on the input parameters of the trials

**Anything else you would like to add:**
When changing a parameter from `int` to `double`, the step has effect. Is this because this field works only for `double` type parameters? Is this documented somewhere?

**Environment:**

- Kubeflow version: 1.0
- Minikube version: 1.2.0 (MiniKF latests)
- Kubernetes version: 1.14
