### ISSUE TITLE
Failed specifying service account in Katib ConfigMap 

### ISSUE THREAD

**Issue by Felihong** [kubeflow/katib#1135]
Hi there, 

to grant Katib experiment pods permissions of accessing GCP storage bucket, I modified the ConfigMap `katib-config` to specify pods with algorithm random using service account `default-editor` instead of `default`:
```
suggestion: |-
    {
      "random": {
        "image": "gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperopt:v0.8.0",
        "serviceAccountName": "default-editor"
      },
      "grid": {
        "image": "gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-chocolate:v0.8.0"
      },
      "hyperband": {
        "image": "gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperband:v0.8.0"
      },
      "bayesianoptimization": {
        "image": "gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-skopt:v0.8.0"
      },
      "tpe": {
        "image": "gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperopt:v0.8.0"
      },
      "nasrl": {
        "image": "gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-nasrl:v0.8.0",
        "imagePullPolicy": "Always",
        "resources": {
          "limits": {
            "memory": "200Mi"
          }
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"metrics-collector-sidecar":"{\n  \"StdOut\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.8.0\"\n  },\n  \"File\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.8.0\"\n  },\n  \"TensorFlowEvent\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/tfevent-metrics-collector:v0.8.0\",\n    \"resources\": {\n      \"limits\": {\n        \"memory\": \"1Gi\"\n      }\n    }\n  }\n}","suggestion":"{\n  \"random\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperopt:v0.8.0\",\n    \"serviceAccountName\": \"default-editor\"\n  },\n  \"grid\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-chocolate:v0.8.0\"\n  },\n  \"hyperband\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperband:v0.8.0\"\n  },\n  \"bayesianoptimization\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-skopt:v0.8.0\"\n  },\n  \"tpe\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperopt:v0.8.0\"\n  },\n  \"nasrl\": {\n    \"image\": \"gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-nasrl:v0.8.0\",\n    \"imagePullPolicy\": \"Always\",\n    \"resources\": {\n      \"limits\": {\n        \"memory\": \"200Mi\"\n      }\n    }\n  }\n}"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"katib-config","namespace":"kubeflow"}}
  creationTimestamp: "2020-03-08T16:35:03Z"
  labels:
    app.kubernetes.io/component: katib
    app.kubernetes.io/instance: katib-controller-0.8.0
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: katib-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: 0.8.0
  name: katib-config
  namespace: kubeflow
```

However, once I started my experiments, it seems like the pods are still running with the default service account, below a snippet of pod specification:
```
apiVersion: v1
kind: Pod
spec:
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-kubeflow-kubeflow-cpu-pool-v1-80cb5b9f-8vh1
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
```
It seems like the ConfigMap failed to take an effect, or did I miss something here? Is there a way to grant more permissions to the `default` service account in user's profile? 

Thanks in advance for your help! 

**Environment:**

- Kubeflow version: `v1.0`
- Kubernetes version: (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): `Ubuntu 18.04.3 LTS`

**Comment by andreyvelich** [comment]
@Felihong Thank you for your issue.

Can you change version of `katib-controller` image to the latest?
I believe in 0.8.0 image we don't have this feature.

**Comment by Felihong** [comment]
Hi @andreyvelich , thanks for your suggestion! 

I changed the image version to `latest` and now I can see the service account has been updated to `default-editor` in the experiment deployment file: 
```
apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      controller-tools.k8s.io: "1.0"
      deployment: random-example-random
      experiment: random-example
      suggestion: random-example
    spec:
      containers:
      - image: gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperopt:v0.8.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:6789
            - -service=manager.v1alpha3.Suggestion
          failureThreshold: 12
          initialDelaySeconds: 10
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 1
        name: suggestion
        ports:
        - containerPort: 6789
          name: katib-api
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default-editor
      serviceAccountName: default-editor
      terminationGracePeriodSeconds: 30
```

However the Pods generated are stilling holding SA `default`:
```
apiVersion: v1
kind: Pod
metadata:
  name: random-example-n6gq5ct4-qbjmr
spec:
  containers:
  - args:
    - python3 /opt/katib_experiment/katib_optimizer.py --learning-rate=0.06654698007515465
      --no-rounds=89 --embed-stack=news-forward 1>/var/log/katib/metrics.log 2>&1
      && echo completed > /var/log/katib/$$$$.pid
    command:
    - sh
    - -c
    image: [USER_IMAGE]
    imagePullPolicy: IfNotPresent
    name: random-example-n6gq5ct4
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-4h4tq
      readOnly: true
    - mountPath: /var/log/katib
      name: metrics-volume
  - args:
    - -t
    - random-example-n6gq5ct4
    - -m
    - final-error;train-error;eval-error
    - -s
    - katib-db-manager.kubeflow:6789
    - -path
    - /var/log/katib/metrics.log
    - -f
    - ([\w|-]+)\s*:\s*((-?\d+)(\.\d+)?)
    image: gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.8.0
    imagePullPolicy: IfNotPresent
    name: metrics-logger-and-collector
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-kubeflow-kubeflow-cpu-pool-v1-80cb5b9f-8vh1
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
```

Did I misunderstand something here? And btw. what's the best practice for granting API permissions when using Katib? Should I mount the SA token in the container image instead? 

Thanks for your help!
