### ISSUE TITLE
Goptuna Suggestion Katib integration

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1152]
/kind feature

For Katib integration with Goptuna we have to make these steps:

- [x] Suggestion source code

- [x] CMA-ES yaml example

- [x] Training container source code, if it is not possible to use mxnet example: https://github.com/kubeflow/katib/tree/master/examples/v1alpha3/mxnet-mnist

- [x] Build Goptuna image in CI and update Katib config

- [x] Create e2e test in CI

/cc @c-bata

**Comment by c-bata** [comment]
Thank you!

/assign @c-bata

**Comment by andreyvelich** [comment]
@c-bata I can help you with 4th and 5th step related to CI.
Can you submit yaml example and check training container, please?

**Comment by c-bata** [comment]
Sure! Thank you.

**Comment by c-bata** [comment]
I'm in two minds which example should I add:

## mxnet-mninst example

![ScreenShot 2020-04-17 12 54 52](https://user-images.githubusercontent.com/5564044/79530579-a76dad80-80aa-11ea-8c3f-3b318efec1ee.png)

<details>

<summary>experiment</summary>

This experiment is almost the same of `tpe-example`. Please note that Goptuna's CMA-ES does not support categorical search space. So `--optimizer` param is sampled by Goptuna independent sampler (default: random sampler).

```
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: cmaes-example
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
  algorithm:
    algorithmName: cmaes
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: --num-layers
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "5"
    - name: --optimizer
      parameterType: categorical
      feasibleSpace:
        list:
        - sgd
        - adam
        - ftrl
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: docker.io/kubeflowkatib/mxnet-mnist
                  command:
                  - "python3"
                  - "/opt/mxnet-mnist/mnist.py"
                  - "--batch-size=64"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
```

</details>

## Rosenbrock function

https://en.wikipedia.org/wiki/Himmelblau%27s_function

This function is quite simple and we can evaluate so fast. But it's not a realistic problem and we need to add CI setting to build docker image.

```python
import argparse
import logging

logging.basicConfig(filename='/var/log/katib.log', level=logging.DEBUG)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--x1", dest='x1', type=float)
    parser.add_argument("--x2", dest='x2', type=float)

    args = parser.parse_args()
    print(args.x1, args.x2)

    evaluation = (args.x1 ** 2 + args.x2 - 11.0) ** 2 + (args.x1 + args.x2 ** 2 - 7.0) ** 2

    metric_msg = f'{{metricName: evaluation, metricValue: {evaluation:.4f}}};'
    logging.info(metric_msg)
    print(metric_msg)


if __name__ == '__main__':
    main()
```

```
FROM python:3-alpine

ADD main.py /usr/src/main.py
WORKDIR /usr/src
```

<details>

<summary>experiment</summary>


```yaml
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: cmaes-example
spec:
  objective:
    type: minimize
    goal: 0.0001
    objectiveMetricName: evaluation
  algorithm:
    algorithmName: cmaes
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
          - "{metricName: ([\\w|-]+), metricValue: ((-?\\d+)(\\.\\d+)?)}"
      fileSystemPath:
        path: "/var/log/katib.log"
        kind: File
    collector:
      kind: File
  parallelTrialCount: 2
  maxTrialCount: 250
  maxFailedTrialCount: 3
  parameters:
    - name: x1
      parameterType: double
      feasibleSpace:
        min: "-10"
        max: "10"
    - name: x2
      parameterType: iint
      feasibleSpace:
        min: "-10"
        max: "10"
        step: "2"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: docker.io/cbata/hello-katib-quadratic-function
                  command:
                  - "python3"
                  - "main.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "--{{.Name}} {{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
```

</details>
