### ISSUE TITLE
additionalMetricNames does not seem to work for TensorFlowEvent

### ISSUE THREAD

**Issue by sadeel** [kubeflow/katib#1188]
/kind bug

**What steps did you take and what happened:**
I have an experiment, which looks like this:
```yaml
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: hyperparameter-tuning
spec:
  objective:
    type: minimize
    goal: 0.00
    objectiveMetricName: epoch_loss
    additionalMetricNames:
    - epoch_binary_accuracy
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: /tmp/tensorboard_logs/validation
        kind: Directory
    collector:
      kind: TensorFlowEvent
```

Individual trials do not seem to report the objective metric or other the additional metrics. However, if I remove the additionalMetricNames altogether, it seems to work fine.
![none](https://user-images.githubusercontent.com/5696932/81990384-10dece80-960d-11ea-8dae-545ce508efb4.png)

**What did you expect to happen:**
All metrics to be populated.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
