### ISSUE TITLE
Failed to reconcile: no matches for kind "TFJob" in version "kubeflow.org/v1"

### ISSUE THREAD

**Issue by devxoxo** [kubeflow/katib#1228]
/kind bug

I tried to use TFJob and PyTorchJob on **GKE cluster**, but having the following issue.
`Failed to reconcile: no matches for kind "TFTJob" in version "kubeflow.org/v1"`

```
(base) jieunui-MacBookPro:v1alpha3 jieun$ kubectl describe trial tfjob-example-25b847dg -n kubeflow
Name:         tfjob-example-25b847dg
Namespace:    kubeflow
Labels:       experiment=tfjob-example
Annotations:  <none>
API Version:  kubeflow.org/v1alpha3
Kind:         Trial
Metadata:
  Creation Timestamp:  2020-06-22T07:43:42Z
  Finalizers:
    clean-metrics-in-db
  Generation:  1
  Owner References:
    API Version:           kubeflow.org/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Experiment
    Name:                  tfjob-example
    UID:                   0bef8e53-b45c-11ea-a1e3-42010ab20010
  Resource Version:        4320903
  Self Link:               /apis/kubeflow.org/v1alpha3/namespaces/kubeflow/trials/tfjob-example-25b847dg
  UID:                     187a071f-b45c-11ea-a1e3-42010ab20010
Spec:
  Metrics Collector:
    Collector:
      Kind:  TensorFlowEvent
    Source:
      File System Path:
        Kind:  Directory
        Path:  /train
  Objective:
    Goal:                   0.99
    Objective Metric Name:  accuracy_1
    Type:                   maximize
  Parameter Assignments:
    Name:    --learning_rate
    Value:   0.036271657073908566
    Name:    --batch_size
    Value:   136
  Run Spec:  apiVersion: "kubeflow.org/v1"
kind: TFJob
metadata:
  name: tfjob-example-25b847dg
  namespace: kubeflow
spec:
 tfReplicaSpecs:
  Worker:
    replicas: 1 
    restartPolicy: OnFailure
    template:
      spec:
        containers:
          - name: tensorflow 
            image: gcr.io/kubeflow-ci/tf-mnist-with-summaries:1.0
            imagePullPolicy: Always
            command:
              - "python"
              - "/var/tf_mnist/mnist_with_summaries.py"
              - "--log_dir=/train/metrics"
              - "--learning_rate=0.036271657073908566"
              - "--batch_size=136"
Status:
  Completion Time:  <nil>
  Conditions:
    Last Transition Time:  2020-06-22T07:43:42Z
    Last Update Time:      2020-06-22T07:43:42Z
    Message:               Trial is created
    Reason:                TrialCreated
    Status:                True
    Type:                  Created
  Start Time:              2020-06-22T07:43:42Z
Events:
  Type     Reason           Age                From              Message
  ----     ------           ----               ----              -------
  Warning  ReconcileFailed  5s (x12 over 39s)  trial-controller  Failed to reconcile: no matches for kind "TFJob" in version "kubeflow.org/v1"
```

I also tried to change apiVersion from "kubeflow.org/v1" to "kubeflow.org/v1beta2" referring to this [link](https://github.com/kubeflow/katib/issues/661).
But the result is the same.
`Failed to reconcile: no matches for kind "TFJob" in version "kubeflow.org/v1beta2"`

**The situation of PyTorchJob is the same.**

How can I fix this problem?

-------------------------------------------------------------------------------------
I installed Katib using [deploy.sh](https://github.com/kubeflow/katib/blob/master/scripts/v1alpha3/deploy.sh).
For installing tfjob and pytorchjob operator, I ran the following
```
git clone https://github.com/kubeflow/manifests

cd "${MANIFESTS_DIR}/tf-training/tf-job-crds/base"
kustomize build . | kubectl apply -f -
cd "${MANIFESTS_DIR}/tf-training/tf-job-operator/base"
kustomize build . | kubectl apply -n kubeflow -f -

cd "${MANIFESTS_DIR}/pytorch-job/pytorch-job-crds/base"
kustomize build . | kubectl apply -f -
cd "${MANIFESTS_DIR}/pytorch-job/pytorch-operator/base/"
kustomize build . | kubectl apply -n kubeflow -f -
```

I used this yaml.
```
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow
  name: tfjob-example
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy_1
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: /train
        kind: Directory
    collector:
      kind: TensorFlowEvent
  parameters:
    - name: --learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: --batch_size
      parameterType: int
      feasibleSpace:
        min: "100"
        max: "200"
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: TFJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           tfReplicaSpecs:
            Worker:
              replicas: 1 
              restartPolicy: OnFailure
              template:
                spec:
                  containers:
                    - name: tensorflow 
                      image: gcr.io/kubeflow-ci/tf-mnist-with-summaries:1.0
                      imagePullPolicy: Always
                      command:
                        - "python"
                        - "/var/tf_mnist/mnist_with_summaries.py"
                        - "--log_dir=/train/metrics"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}
```

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):
