### ISSUE TITLE
Error when setting a hyperparamter in a list of doubles

### ISSUE THREAD

**Issue by xuhdev** [kubeflow/katib#1229]
/kind bug

**What steps did you take and what happened:**

In hyperparamter tuning, I selected `random` algorithm, and set a sole hyperparamter `--learning_rate`, typed `double`, and set it to a list of two numbers, 0.01 and 0.001. All of `ParallelTrialCount`, `MaxTrialCount`, and `MaxFailedTrialCount` are set to 1.

In the log, the following error is shown:

```
 ValueError: could not convert string to float: 
ERROR:grpc._server:Exception calling application: could not convert string to float: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grpc/_server.py", line 434, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/usr/src/app/github.com/kubeflow/katib/pkg/suggestion/v1alpha3/hyperopt/service.py", line 34, in GetSuggestions
    search_space=search_space)
  File "/usr/src/app/github.com/kubeflow/katib/pkg/suggestion/v1alpha3/hyperopt/base_service.py", line 36, in __init__
    self.create_hyperopt_domain()
  File "/usr/src/app/github.com/kubeflow/katib/pkg/suggestion/v1alpha3/hyperopt/base_service.py", line 53, in create_hyperopt_domain
    float(param.min), 
```

**What did you expect to happen:**

Should proceed to my training script normally.

**Misc info**

For hyerpot, I'm using `gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperopt:latest`.

**Environment:**

- Kubeflow version: 1.0.2
- Minikube version:
```
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
```
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by andreyvelich** [comment]
Hi @xuhdev!
Can you show your experiment yaml, please?

**Comment by xuhdev** [comment]
Here you go!

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Trial}}
  namespace: {{.NameSpace}}
spec:
  template:
    spec:
      containers:
      - name: {{.Trial}}
        image: docker.io/my/image
        resources:
          requests:
            memory: "56Gi"
            cpu: "20"
          limits:
            memory: "56Gi"
            cpu: "20"
        command:
        - "python3"
        - "train.py"
        - "--result_path"
        - "./result"
        {{- with .HyperParameters}}
        {{- range .}}
        - "{{.Name}}={{.Value}}"
        {{- end}}
        {{- end}}
        env:
          - name: S3_ENDPOINT_URL
            value: s3.us.cloud-object-storage.appdomain.cloud
          - name: S3_ACCESS_KEY_ID
            value: xxxxxxxxx
          - name: S3_SECRET_ACCESS_KEY
            value: xxxxxxxxxxxxxxxxxxxxxxxxxxx
          - name: JOB_ID
            value: {{.Trial}}
      restartPolicy: Never
```
