### ISSUE TITLE
[Documentation] Information about Trial meta injection in template

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1280]
/kind feature

After this PR: https://github.com/kubeflow/katib/pull/1259, user can use Trial metadata in Trial parameters.
We should explain how to use substitution in template for metadata parameters.

**Comment by terrykong** [comment]
Hi @andreyvelich . After the merge of the new trial template, is there still a mechanism to get the trial name? For reference, the gotemplate way of referencing it was https://github.com/kubeflow/katib/pull/1202/files#diff-82dc48b655cb8b5eff0c7fe15d75607bL47, but all v1beta1 examples don't have that field anymore. Is there a way of referencing that variable?

The use case here is when running a trial I create intermediate files in a directory that has the same name as the trial that are useful to analyze after the full experiment is run.

**Comment by andreyvelich** [comment]
Hi @terrykong, yes it is possible.

@sperlingxx implemented it in https://github.com/kubeflow/katib/pull/1259.

You can get data from `metadata.name`, `metadata.namespace`, `Kind`, `APIVersion `, `metadata.labels[x]`, `metadata.annotations[x]` from Trial running Job and use it for substitution.

We need to document it.
I will submit PR with example, how you can use these values.

**Comment by terrykong** [comment]
Cool, looking forward to the documentation. Thanks for pointing out the relevant PR.

So I was a little impatient and went ahead and tried to do it myself. Following https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/experiment/manifest/generator_test.go I got it to work, but I'm curious if this design was intended. To make things work I need to specify all the metadata variables I want in the trialParameters, e.g.,

```
trialTemplate:
    trialParameters:
      - name: dummyparam
        description: a dummy parameter
        reference: -dp
      - name: foobar
        description: a dummy parameter
        reference: -foobar
      - name: trialName
        description: the name of the trial
        reference: ${trialSpec.Name}
      - name: trialNamespace
        description: namespace of current trial
        reference: ${trialSpec.Namespace}
      - name: jobKind
        description: job kind of current trial
        reference: ${trialSpec.Kind}
      - name: jobAPIVersion
        description: job API Version of current trial
        reference: ${trialSpec.APIVersion}
```

And I noticed that this works if in my containers command I specify the metadata variables like so:
```
                  echo trialParameters.trialName="${trialParameters.trialName}";
                  echo trialParameters.trialNamespace="${trialParameters.trialNamespace}";
                  echo trialParameters.jobKind="${trialParameters.jobKind}";
                  echo trialParameters.jobAPIVersion="${trialParameters.jobAPIVersion}";
```

But what I'm curious about is why directly referencing the variable from the `trialSpec` this isn't supported:

```
                  echo trialSpec.Name=${trialSpec.Name};
                  echo trialSpec.Namespace=${trialSpec.Namespace};
                  echo trialSpec.Kind=${trialSpec.Kind};
                  echo trialSpec.APIVersion=${trialSpec.APIVersion};
```
