### ISSUE TITLE
About a behavior when metrics collector is None.

### ISSUE THREAD

**Issue by Lee-Yeongjae** [kubeflow/katib#1419]
I'm using Katib v0.10.0.
When the metrics collector is None, both experiments and trials remain in the "Running" state even though the pod state is "Completed".
Is there a way to verify the end state of the experiment successfully?

**Information**
- Experiments
```
# kubectl get experiments -n kubeflow
NAME             TYPE      STATUS   AGE
tfjob-example1   Running   True     7m40s
```
- Suggestions
```
kubectl get suggestions -n kubeflow
NAME             TYPE      STATUS   REQUESTED   ASSIGNED   AGE
tfjob-example1   Running   True     1           1          7m47s
```
- Trials
```
# kubectl get trials -n kubeflow
NAME                      TYPE      STATUS   AGE
tfjob-example1-vskkm677   Running   True     7m17s
```
- Pods
```
# kubectl get pod -n kubeflow
NAME                                     READY   STATUS      RESTARTS   AGE
tfjob-example1-random-656bf96dd9-kwv5n   1/1     Running     0          6m36s
tfjob-example1-vskkm677-worker-0         0/1     Completed   0          6m23s
```

- Manifest
```
apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: kubeflow
  name: tfjob-example1
spec:
  parallelTrialCount: 1
  maxTrialCount: 1
  maxFailedTrialCount: 1
  objective:
    objectiveMetricName: hptuning-metric
    type: maximize
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    collector:
      kind: None
  parameters:
    - name: learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: batch_size
      parameterType: int
      feasibleSpace:
        min: "100"
        max: "200"
  trialTemplate:
    primaryContainerName: tensorflow
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: learning_rate
      - name: batchSize
        description: Batch Size
        reference: batch_size
    trialSpec:
      apiVersion: "kubeflow.org/v1"
      kind: TFJob
      spec:
        tfReplicaSpecs:
          Worker:
            replicas: 1
            restartPolicy: OnFailure
            template:
              spec:
                containers:
                  - name: tensorflow
                    image: gcr.io/kubeflow-ci/tf-mnist-with-summaries:1.0
                    imagePullPolicy: IfNotPresent
                    command:
                      - "python"
                      - "/var/tf_mnist/mnist_with_summaries.py"
                      - "--log_dir=/metrics/test"
                      - "--learning_rate=${trialParameters.learningRate}"
                      - "--batch_size=${trialParameters.batchSize}"
                    volumeMounts:
                    - mountPath: /metrics
                      name: metrics
                volumes:
                - name: metrics
                  persistentVolumeClaim:
                    claimName: test-pvc
```

**Environment:**
- On-prem
- Kubeflow version (`kfctl version`): None
- Minikube version (`minikube version`): None
- Katib version: v0.10.0
- Kubernetes version: (use `kubectl version`): v1.19.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS(4.15.0-97-generic)
