### ISSUE TITLE
xgboost katib hyperparameter tuning failing on katib

### ISSUE THREAD

**Issue by Josepholaidepetro** [kubeflow/katib#1495]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I ran this xgboost YAML file that I created but the trials keep on failing. @andreyvelich 
```
apiVersion: kubeflow.org/v1alpha3
kind: Experiment
metadata:
  name: new1
  namespace: demo01
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    kind: StdOut
  parameters:
    - name: n_estimators
      parameterType: categorical
      feasibleSpace:
        list:
          - 800
          - 1000
    - name: learning_rate
      parameterType: categorical
      feasibleSpace:
        list:
          - 0.123
          - 0.145
    - name: max_depth
      parameterType: categorical
      feasibleSpace:
        list:
          - 10
          - 12
    - name: reg_alpha
      parameterType: categorical
      feasibleSpace:
        list:
          - 0.7
          - 0.8
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: n_estimators
        description: N estimators for the model
        reference: n_estimators
      - name: learning_rate
        description: Learning rate for the model
        reference: learning_rate
      - name: max_depth
        description: Max depth for the model
        reference: max_depth
      - name: reg_alpha
        description: Reg alpha for the model
        reference: reg_alpha
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: training-container
                image: "mavencodev/xgb_hack:1.2"
                command:
                  - python
                  - -u
                  - /umoja.py
                args:
                  - "--n_estimators=${trialParameters.n_estimators}"
                  - "--learning_rate=${trialParameters.learning_rate}"
                  - "--max_depth=${trialParameters.max_depth}"
                  - "--reg_alpha=${trialParameters.reg_alpha}"
            restartPolicy: Never
```
This is a link to my python script. https://github.com/Josepholaidepetro/Umojahack/blob/main/umoja.py

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version (`kfctl version`):
- Minikube version (`minikube version`):
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
