### ISSUE TITLE
Grid Search stuck when parallelTrialCount < maxTrialCount

### ISSUE THREAD

**Issue by sidpalas** [kubeflow/katib#1534]
/kind bug

**What steps did you take and what happened:**

I created an experiment to perform a grid search, set `maxTrialCount` equal to the size of the grid, and set `parallelTrialCount < maxTrialCount`.

The first set of parallel trials completes successfully, but at some point after that the experiment gets stuck. The suggestion shows requested > assigned and has the following warning:
`Warning  ReconcileError  4s (x12 over 31s)  suggestion-controller  The response contains unexpected trials`

**What did you expect to happen:**
Experiment to execute trials for each point in the parameter space and then complete.

**Anything else you would like to add:**

I am running this image for the katib-controller: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller:latest (I also tested with gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller:v0.8.0)

The issue seems like it is likely related to https://github.com/kubeflow/katib/issues/1494

If I set `parallelTrialCount >= maxTrialCount` (enabling all runs to execute immediately) the experiment succeeds.

**Environment:**

- Kubeflow version (`kfctl version`): v1.0.1
- Minikube version (`minikube version`): N/A
- Kubernetes version: (use `kubectl version`): v1.18.17-gke.100
- OS (e.g. from `/etc/os-release`):

---
experiment.yaml:
```
apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: sid
  labels:
    controller-tools.k8s.io: "1.0"
  name: minimal-grid
spec:
  objective:
    type: maximize
    goal: 999999
    objectiveMetricName: value
  resumePolicy: Never
  algorithm:
    algorithmName: grid
  parallelTrialCount: 5
  maxTrialCount: 15
  maxFailedTrialCount: 3
  parameters:
    - name: --param_1
      parameterType: int
      feasibleSpace:
        min: "0"
        max: "15"
  trialTemplate:
    goTemplate:
      rawTemplate: |-
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {{.Trial}}
          namespace: {{.NameSpace}}
        spec:
          template:
            spec:
              containers:
              - name: {{.Trial}}
                image: <IMAGE>
                command:
                - "python3"
                - "return_param_value.py"
                {{- with .HyperParameters}}
                {{- range .}}
                - "{{.Name}}={{.Value}}"
                {{- end}}
                {{- end}}
              restartPolicy: Never
```

Result of `kubectl describe suggestion <suggestion-name>`:
```
Name:         minimal-grid
Namespace:    sid
Labels:       controller-tools.k8s.io=1.0
Annotations:  <none>
API Version:  kubeflow.org/v1alpha3
Kind:         Suggestion
Metadata:
  Creation Timestamp:  2021-05-18T05:58:39Z
  Generation:          9
  Managed Fields:
    API Version:  kubeflow.org/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:controller-tools.k8s.io:
        f:ownerReferences:
      f:spec:
        .:
        f:algorithmName:
        f:requests:
      f:status:
        .:
        f:conditions:
        f:startTime:
        f:suggestionCount:
        f:suggestions:
    Manager:    katib-controller
    Operation:  Update
    Time:       2021-05-18T05:58:56Z
  Owner References:
    API Version:           kubeflow.org/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Experiment
    Name:                  minimal-grid
    UID:                   90e538b2-5858-45d2-af0e-38c0837d6a8d
  Resource Version:        69731263
  Self Link:               /apis/kubeflow.org/v1alpha3/namespaces/sid/suggestions/minimal-grid
  UID:                     3875d508-b3ee-4426-88a7-1b307c381249
Spec:
  Algorithm Name:  grid
  Requests:        13
Status:
  Conditions:
    Last Transition Time:  2021-05-18T05:58:39Z
    Last Update Time:      2021-05-18T05:58:39Z
    Message:               Suggestion is created
    Reason:                SuggestionCreated
    Status:                True
    Type:                  Created
    Last Transition Time:  2021-05-18T05:58:54Z
    Last Update Time:      2021-05-18T05:58:54Z
    Message:               Deployment is ready
    Reason:                DeploymentReady
    Status:                True
    Type:                  DeploymentReady
    Last Transition Time:  2021-05-18T05:58:55Z
    Last Update Time:      2021-05-18T05:58:55Z
    Message:               Suggestion is running
    Reason:                SuggestionRunning
    Status:                True
    Type:                  Running
  Start Time:              2021-05-18T05:58:39Z
  Suggestion Count:        8
  Suggestions:
    Name:  minimal-grid-dq75pd5j
    Parameter Assignments:
      Name:   --param_1
      Value:  0
    Name:     minimal-grid-jsl78k9b
    Parameter Assignments:
      Name:   --param_1
      Value:  1
    Name:     minimal-grid-nbhlss7f
    Parameter Assignments:
      Name:   --param_1
      Value:  2
    Name:     minimal-grid-p87q65dk
    Parameter Assignments:
      Name:   --param_1
      Value:  3
    Name:     minimal-grid-dt2s5jd5
    Parameter Assignments:
      Name:   --param_1
      Value:  4
    Name:     minimal-grid-jxtrdnk9
    Parameter Assignments:
      Name:   --param_1
      Value:  6
    Name:     minimal-grid-l2t2gpc8
    Parameter Assignments:
      Name:   --param_1
      Value:  9
    Name:     minimal-grid-4dpdlj2v
    Parameter Assignments:
      Name:   --param_1
      Value:  13
Events:
  Type     Reason          Age               From                   Message
  ----     ------          ----              ----                   -------
  Warning  ReconcileError  0s (x8 over 15s)  suggestion-controller  The response contains unexpected trials
```

**Comment by andreyvelich** [comment]
Thank you for creating this @sidpalas.
It might be this issue: https://github.com/kubeflow/katib/issues/1494#issuecomment-808377111.
I would recommend to use the latest Katib release to debug this.
`v1alpha3` was deprecated 1 year ago.

**Comment by sidpalas** [comment]
Thanks @andreyvelich -- are there any special considerations I need to make when upgrading to the newer versions of Katib (e.g. related to DB migrations)? 

I know for Kubeflow Pipelines upgrading in-place wasn't supported for some versions.

**Comment by andreyvelich** [comment]
Unfortunately, we don't support in-place upgrade currently.
You should manually delete all v1alpha3 Katib resources and use `make deploy` to use the latest version.

**Comment by andreyvelich** [comment]
Before clean-up resources you should delete all Experiments:
`kubectl delete experiment --all-namespaces --all`

**Comment by sidpalas** [comment]
I deployed a new standalone Katib deployment in a separate cluster to test and was able to reproduce this result.

I used the commit corresponding to the latest release (https://github.com/kubeflow/katib/releases/tag/v0.11.0). This deployed katib-controller with image: `docker.io/kubeflowkatib/katib-controller:v0.11.0`

The updated experiment spec (to now be compatible with `v1beta1` is:

```
apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: kubeflow
  name: grid-example
spec:
  objective:
    type: maximize
    goal: 999999
    objectiveMetricName: value
  algorithm:
    algorithmName: grid
  parallelTrialCount: 3
  maxTrialCount: 15
  maxFailedTrialCount: 3
  parameters:
    - name: param_1
      parameterType: int
      feasibleSpace:
        min: "0"
        max: "15"
  trialTemplate:
    primaryContainerName: main-container
    trialParameters:
      - name: param_1
        description: value passed as input
        reference: param_1
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: main-container
                image: gcr.io/gauntlet-sid-experiment/simple-katib:katib-proof-of-concept
                command:
                  - "python3"
                  - "return_param_value.py"
                  - "--param_1=${trialParameters.param_1}"
            restartPolicy: Never
```

and the result of `kubectl describe suggestion -n kubeflow grid-example` is: 

Name:         grid-example
Namespace:    kubeflow
Labels:       <none>
Annotations:  <none>
API Version:  kubeflow.org/v1beta1
Kind:         Suggestion
Metadata:
  Creation Timestamp:  2021-05-18T15:26:24Z
  Generation:          11
  Managed Fields:
    API Version:  kubeflow.org/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:ownerReferences:
      f:spec:
        .:
        f:algorithm:
          .:
          f:algorithmName:
        f:requests:
        f:resumePolicy:
      f:status:
        .:
        f:conditions:
        f:startTime:
        f:suggestionCount:
        f:suggestions:
    Manager:    katib-controller
    Operation:  Update
    Time:       2021-05-18T15:27:12Z
  Owner References:
    API Version:           kubeflow.org/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Experiment
    Name:                  grid-example
    UID:                   cf9b0436-ec55-4aa1-a456-315e6f56dca2
  Resource Version:        7951
  Self Link:               /apis/kubeflow.org/v1beta1/namespaces/kubeflow/suggestions/grid-example
  UID:                     dce1ad9b-507c-4745-a62b-188c63eaf2c0
Spec:
  Algorithm:
    Algorithm Name:  grid
  Requests:          13
  Resume Policy:     LongRunning
Status:
  Conditions:
    Last Transition Time:  2021-05-18T15:26:24Z
    Last Update Time:      2021-05-18T15:26:24Z
    Message:               Suggestion is created
    Reason:                SuggestionCreated
    Status:                True
    Type:                  Created
    Last Transition Time:  2021-05-18T15:27:11Z
    Last Update Time:      2021-05-18T15:27:11Z
    Message:               Deployment is ready
    Reason:                DeploymentReady
    Status:                True
    Type:                  DeploymentReady
    Last Transition Time:  2021-05-18T15:27:11Z
    Last Update Time:      2021-05-18T15:27:11Z
    Message:               Suggestion is running
    Reason:                SuggestionRunning
    Status:                True
    Type:                  Running
  Start Time:              2021-05-18T15:26:24Z
  Suggestion Count:        10
  Suggestions:
    Name:  grid-example-8gcfgw52
    Parameter Assignments:
      Name:   param_1
      Value:  0
    Name:     grid-example-mqrrmk86
    Parameter Assignments:
      Name:   param_1
      Value:  1
    Name:     grid-example-wd8bq4gd
    Parameter Assignments:
      Name:   param_1
      Value:  2
    Name:     grid-example-ngdqdvkx
    Parameter Assignments:
      Name:   param_1
      Value:  3
    Name:     grid-example-mp9dvpld
    Parameter Assignments:
      Name:   param_1
      Value:  4
    Name:     grid-example-cvlcq227
    Parameter Assignments:
      Name:   param_1
      Value:  6
    Name:     grid-example-nwzqq9kg
    Parameter Assignments:
      Name:   param_1
      Value:  7
    Name:     grid-example-wvlvn4nv
    Parameter Assignments:
      Name:   param_1
      Value:  8
    Name:     grid-example-k5bj8j2g
    Parameter Assignments:
      Name:   param_1
      Value:  13
    Name:     grid-example-lvtzm4r6
    Parameter Assignments:
      Name:   param_1
      Value:  14
Events:
  Type     Reason          Age                   From                   Message
  ----     ------          ----                  ----                   -------
  Warning  ReconcileError  62s (x17 over 3m41s)  suggestion-controller  The response contains unexpected trials
```

It seems to start okay, but at some point after the first parallel batch, the suggestion-controller hits this condition: https://github.com/kubeflow/katib/blob/acec1e2d7bb5f93143311d96440285ab3ac7de73/pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go#L117 and the experiment gets stuck...

**Comment by sidpalas** [comment]
I did just notice another interesting thing. Even though my experiment has a single integer parameter with 15 possible values:
```
  parameters:
    - name: param_1
      parameterType: int
      feasibleSpace:
        min: "0"
        max: "15"
```
The Suggestion seems to skip some of the possible values: `0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 13, 14`  (for this experiment it is missing `3, 8, 12`)

Is this expected?
