### ISSUE TITLE
katib NAS trial created for feedforward architecture but no SUGGESTION was created

### ISSUE THREAD

**Issue by Jaydeemourg** [kubeflow/katib#1561]
/kind bug

**What steps did you take and what happened:**
i created a training script to train my dnn model, then package the script in an image. A YAML file for the Neural Architecture Search (NAS) experiment was then created. upon running the experiment, the trials created as shown below but no suggestions were made; am i missing something

**output of** `kubectl logs ai-nalyze-tuning-nas-0-enas-6f5578d676-7cdnk -n ki-user -c suggestion`

```
Validate Algorithm Settings start
All Experiment Settings are Valid
----------------------------------------------------------------------------------------------------
Setting Up Suggestion for Experiment ai-nalyze-tuning-nas-0
----------------------------------------------------------------------------------------------------

>>> Search Space for Experiment ai-nalyze-tuning-nas-0
Operation ID: 
        0
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 1
        neurons: 32

Operation ID: 
        1
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 1
        neurons: 48

Operation ID: 
        2
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 1
        neurons: 64

Operation ID: 
        3
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 1
        neurons: 96

Operation ID: 
        4
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 1
        neurons: 128

Operation ID: 
        5
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 7
        neurons: 32

Operation ID: 
        6
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 7
        neurons: 48

Operation ID: 
        7
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 7
        neurons: 64

Operation ID: 
        8
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 7
        neurons: 96

Operation ID: 
        9
Operation Type: 
        feedforward
Operations Parameters:
        num-layers: 7
        neurons: 128

There are 10 operations in total.

>>> Parameters of LSTM Controller for Experiment ai-nalyze-tuning-nas-0

controller_hidden_size:         64
controller_temperature:         5.0
controller_tanh_const:          2.25
controller_entropy_weight:      1e-05
controller_baseline_decay:      0.999
controller_learning_rate:       5e-05
controller_skip_target:         0.4
controller_skip_weight:         0.8
controller_train_steps:         50
controller_log_every_steps:     10

>>> Building Controller

>>> Building Controller Parameters

>>> Controller has 42368 Trainable params

>>> Building Controller Sampler

>>> Suggestion for Experiment ai-nalyze-tuning-nas-0 has been initialized.

----------------------------------------------------------------------------------------------------
Suggestion Step 0 for Experiment ai-nalyze-tuning-nas-0
----------------------------------------------------------------------------------------------------

>>> RequestNumber:              2

>>> First time running suggestion for ai-nalyze-tuning-nas-0. Random architecture will be given.
2021-06-24 12:46:52.414608: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-06-24 12:46:52.419136: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599990000 Hz
2021-06-24 12:46:52.419496: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f5d98b89550 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-24 12:46:52.419517: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

>>> New Neural Network Architecture Candidate #0 (internal representation):
[[3], [1, 0], [0, 0, 1], [9, 0, 1, 0], [2, 0, 0, 1, 1], [7, 1, 1, 0, 1, 1], [8, 1, 1, 0, 1, 1, 0]]

>>> Corresponding Seach Space Description:
{'num_layers': 7, 'input_sizes': [11], 'output_sizes': [2], 'embedding': {'3': {'opt_id': 3, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '1', 'neurons': '96'}}, '1': {'opt_id': 1, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '1', 'neurons': '48'}}, '0': {'opt_id': 0, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '1', 'neurons': '32'}}, '9': {'opt_id': 9, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '7', 'neurons': '128'}}, '2': {'opt_id': 2, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '1', 'neurons': '64'}}, '7': {'opt_id': 7, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '7', 'neurons': '64'}}, '8': {'opt_id': 8, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '7', 'neurons': '96'}}}}

>>> New Neural Network Architecture Candidate #1 (internal representation):
[[3], [6, 0], [8, 1, 1], [9, 1, 0, 0], [4, 0, 0, 0, 1], [7, 1, 1, 0, 0, 1], [6, 0, 1, 1, 1, 0, 1]]

>>> Corresponding Seach Space Description:
{'num_layers': 7, 'input_sizes': [11], 'output_sizes': [2], 'embedding': {'3': {'opt_id': 3, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '1', 'neurons': '96'}}, '6': {'opt_id': 6, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '7', 'neurons': '48'}}, '8': {'opt_id': 8, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '7', 'neurons': '96'}}, '9': {'opt_id': 9, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '7', 'neurons': '128'}}, '4': {'opt_id': 4, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '1', 'neurons': '128'}}, '7': {'opt_id': 7, 'opt_type': 'feedforward', 'opt_params': {'num-layers': '7', 'neurons': '64'}}}}

>>> 2 Trials were created for Experiment ai-nalyze-tuning-nas-0
```

**YAML content;**

```
apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: ki-user
  name: ai-nalyze-tuning-nas-0
spec:
  parallelTrialCount: 2
  maxTrialCount: 3
  maxFailedTrialCount: 2
  objective:
    type: maximize
    goal: 0.90
    objectiveMetricName: Categorical_accuracy_eval
  algorithm:
    algorithmName: enas
  nasConfig:
    graphConfig:
      numLayers: 7
      inputSizes:
        - 11
      outputSizes:
        - 2
    operations:
      - operationType: feedforward
        parameters:
          - name: num-layers
            parameterType: categorical
            feasibleSpace:
              list:
                - "1"
                - "7"
          - name: neurons
            parameterType: categorical
            feasibleSpace:
              list:
                - "32"
                - "48"
                - "64"
                - "96"
                - "128"
  trialTemplate:
    primaryContainerName: ai-nalyze-training-container
    trialParameters:
      - name: numberLayers
        description: Number of training model layers
        reference: num-layers
      - name: neurons
        description: Anzahl der Neuronen
        reference: neurons
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: ai-nalyze-training-container
                image: localhost:32000/katibtrainerainalyzenas:v1.0
                command:
                  - python3
                  - -u
                  - aiNalyze_training_Nas.py
                  - --num-layers="${trialParameters.numberLayers}"
                  - --neurons="${trialParameters.neurons}"
            restartPolicy: Never
```

**What did you expect to happen:**
the experiment should run successfully

Anything else you would like to add:
Environment:

`Kubeflow version: 1.3`
`Kubernetes version: (use kubectl version --short): v1.20.7
`
