### ISSUE TITLE
[chore] Upgrade CRDs to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#1581]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

> The api group apiextensions.k8s.io/v1beta1 is no longer served in k8s 1.22 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122
>
> kubeflow APIs need to be upgraded

/cc @alculquicondor

Maybe there is problem about https://github.com/kubernetes/apiextensions-apiserver/issues/50

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
@gaocegege I was able to run Experiments with this CRD and temp `openAPIV3Schema`:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: experiments.kubeflow.org
spec:
  group: kubeflow.org
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Type
          type: string
          jsonPath: .status.conditions[-1:].type
        - name: Status
          type: string
          jsonPath: .status.conditions[-1:].status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
  names:
    kind: Experiment
    singular: experiment
    plural: experiments
    categories:
      - all
      - kubeflow
      - katib
```

To generate `openAPIV3Schema` using `controller-gen` we should make some changes in APIs.
First of all, we have to remove float from our CRDs APIs(https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/common/v1beta1/common_types.go#L100).
Ref issue: https://github.com/kubeflow/katib/issues/889.

@gaocegege @johnugeorge Do we want to switch our CRDs to `apiextensions.k8s.io/v1` at least ?
