### ISSUE TITLE
Katib MySQL reaching max_prepared_stmt_count limit

### ISSUE THREAD

**Issue by midhun1998** [kubeflow/katib#1651]
/kind bug

**What steps did you take and what happened:**
I have been running a lot of trials recently and seems like now the Katib MySQL has reached the `max_prepared_stmt_count`. The same error is seen in Katib UI pod too. I have temporarily increased the max_prepared_stmt_count but seems like it will not be too long until we reach that limit too. I'm attaching a few more details:

Logs of katib-ui pod contains following statement:
```
2021/08/26 11:40:09 GetObservationLog from HP job failed: rpc error: code = Unknown desc = Failed to get ObservationLogs Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
```
Logs of katib-sql contains following statement:
```
Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
```

Few observations from Katib db:
```
+-----------------+---------------+------------+-------------+
| user            | host          | count_star | command     |
+-----------------+---------------+------------+-------------+
| NULL            | NULL          |          0 | COM_QUERY   |
| NULL            | NULL          |          0 | COM_PREPARE |
| event_scheduler | localhost     |          0 | COM_QUERY   |
| event_scheduler | localhost     |          0 | COM_PREPARE |
| root            | localhost     |          0 | COM_QUERY   |
| root            | localhost     |          0 | COM_PREPARE |
| root            | katib-db-manager |          0 | COM_QUERY   |
| root            | katib-db-manager |          0 | COM_PREPARE |
| root            | katib-db-manager |          0 | COM_QUERY   |
| root            | katib-db-manager |          0 | COM_PREPARE |
| root            | katib-db-manager |          0 | COM_QUERY   |
| root            | katib-db-manager |     111952 | COM_PREPARE |
+-----------------+---------------+------------+-------------+
```
```
Prepared_stmt_count                   | 17120
```
```
mysql> show global status like 'com_stmt%';
+-------------------------+--------+
| Variable_name           | Value  |
+-------------------------+--------+
| Com_stmt_execute        | 103062 |
| Com_stmt_close          | 94210  |
| Com_stmt_fetch          | 0      |
| Com_stmt_prepare        | 111318 |
| Com_stmt_reset          | 0      |
| Com_stmt_send_long_data | 0      |
| Com_stmt_reprepare      | 0      |
+-------------------------+--------+
7 rows in set (0.00 sec)
```

**What did you expect to happen:**
- Expected the metric containers to push observations to Katib MySQL.
- Expected Katib UI to continue function normally.

**Anything else you would like to add:**
- Seems like this issue needs to be fixed in the code level rather than increasing the limits.
- Suspecting this [line](https://github.com/kubeflow/katib/blob/acec1e2d7bb5f93143311d96440285ab3ac7de73/pkg/db/v1beta1/mysql/mysql.go#L130) of code. Shouldn't there be a `defer stmt.Close()` line too? 

**Environment:**

- Kubeflow version (`kfctl version`): 1.3.0
- Kubernetes version: (use `kubectl version`): 1.18
- Katib controller version: v0.11.0
- Katib mysql image: mysql:8

**Ref:**
https://github.com/go-sql-driver/mysql/issues/701

**Comment by johnugeorge** [comment]
Thanks for reporting this.
Can you provide your config?

No max trials/parallel trials ?

**Comment by midhun1998** [comment]
Hi @johnugeorge . This wasn't seen for a particular Katib experiment as such. Overtime when we keep running many Katib experiments the prepared statements seems to accumulate and never close. But, To give you an idea of my usual config here it is, Total trials 90 with 10 in parallel.

**Comment by johnugeorge** [comment]
@midhun1998 Can you share the yaml if possible? We have tried for larger number of trials before

**Comment by midhun1998** [comment]
Each training container only injects one metric. Unfortunately, I won't be able to share the image. Here is a sample experiment spec:
```
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
 name: test-a12dqjn5-1-197847055
 namespace: test
spec:
 algorithm:
 algorithmName: random
 maxFailedTrialCount: 2
 maxTrialCount: 90
 metricsCollectorSpec:
 collector:
 kind: StdOut
 source:
 filter:
 metricsFormat:
 - (Loss)\s*:\s*((-?\d+)(\.\d+)?)
 objective:
 goal: 0.001
 metricStrategies:
 - name: Loss
 value: min
 objectiveMetricName: Loss
 type: minimize
 parallelTrialCount: 10
 parameters:
 - feasibleSpace:
 list:
 - "100"
 name: epochs
 parameterType: discrete
 - feasibleSpace:
 list:
 - "0.01"
 - "0.001"
 name: lr
 parameterType: discrete
 - feasibleSpace:
 list:
 - "2"
 - "3"
 - "4"
 name: num_layers
 parameterType: discrete
 - feasibleSpace:
 list:
 - "20"
 - "40"
 - "60"
 - "80"
 - "100"
 name: num_cells
 parameterType: discrete
 - feasibleSpace:
 list:
 - "16"
 - "32"
 - "64"
 name: batch_size
 parameterType: discrete
 resumePolicy: LongRunning
 trialTemplate:
 failureCondition: status.conditions.#(type=="Failed")#|
#(status=="True")#
 primaryContainerName: trial
 successCondition: status.conditions.#(type=="Complete")#|
#(status=="True")#
 trialParameters:
 - description: Number of epoch
 name: epochs
 reference: epochs
 - description: Learning rate for the training model
 name: learningRate
 reference: lr
 - description: Batch size
 name: batchSize
 reference: batch_size
 - description: Number of cells in each layer
 name: numCells
 reference: num_cells
 - description: Number of layers
 name: numLayers
 reference: num_layers
 trialSpec:
 apiVersion: batch/v1
 kind: Job
 spec:
 template:
 metadata:
 annotations:
 sidecar.istio.io/inject: "false"
 spec:
 containers:
 - args:
 - python train.py --epochs=$
{trialParameters.epochs}
 --num_layers=${trialParameters.numLayers} --lr=$
{trialParameters.learningRate}
 --num_cells=${trialParameters.numCells} --
batch_size=${trialParameters.batchSize}
 command:
 - sh
 - -c
 image: <IMAGE>
 name: trial
 restartPolicy: Never
status:
 completionTime: "2021-09-02T20:36:53Z"
 conditions:
 - lastTransitionTime: "2021-09-02T07:04:15Z"
 lastUpdateTime: "2021-09-02T07:04:15Z"
 message: Experiment is created
 reason: ExperimentCreated
 status: "True"
 type: Created
 - lastTransitionTime: "2021-09-02T20:36:53Z"
 lastUpdateTime: "2021-09-02T20:36:53Z"
 message: Experiment is running
 reason: ExperimentRunning
 status: "False"
 type: Running
 - lastTransitionTime: "2021-09-02T20:36:53Z"
 lastUpdateTime: "2021-09-02T20:36:53Z"
 message: Experiment has succeeded because max trial count has
reached
 reason: ExperimentMaxTrialsReached
 status: "True"
 type: Succeeded
 currentOptimalTrial:
 bestTrialName: test-a12dqjn5-1-197847055-8l54px7r
 observation:
 metrics:
 - latest: "16.150574128966348"
 max: "16.150574128966348"
 min: "16.150574128966348"
 name: Loss
 parameterAssignments:
 - name: epochs
 value: "100"
 - name: lr
 value: "0.01"
 - name: num_layers
 value: "2"
 - name: num_cells
 value: "100"
 - name: batch_size
 value: "16"
 startTime: "2021-09-02T07:04:15Z"
 succeededTrialList:
 - test-a12dqjn5-1-197847055-rb8jz5nq
 - test-a12dqjn5-1-197847055-jhlk8l4x
 - test-a12dqjn5-1-197847055-dpc45gs9
 - test-a12dqjn5-1-197847055-69vmlkd5
 - test-a12dqjn5-1-197847055-nrn8jgv6
 - test-a12dqjn5-1-197847055-bqbx7rjp
 - test-a12dqjn5-1-197847055-dx9j2w57
 - test-a12dqjn5-1-197847055-vwdgfbm6
 - test-a12dqjn5-1-197847055-stcfzwxr
 - test-a12dqjn5-1-197847055-qrftmj2m
 - test-a12dqjn5-1-197847055-jh9fvvrt
 - test-a12dqjn5-1-197847055-khjhmkqw
 - test-a12dqjn5-1-197847055-5fj92kkk
 - test-a12dqjn5-1-197847055-hkzvhgqh
 - test-a12dqjn5-1-197847055-hbzm7lwg
 - test-a12dqjn5-1-197847055-sb8pvjzn
 - test-a12dqjn5-1-197847055-g2t6h8r7
 - test-a12dqjn5-1-197847055-qvjw2c8m
 - test-a12dqjn5-1-197847055-q8v9gtn9
 - test-a12dqjn5-1-197847055-m9v6d28h
 - test-a12dqjn5-1-197847055-dr9gcm7v
 - test-a12dqjn5-1-197847055-s4g8wnnb
 - test-a12dqjn5-1-197847055-vv58jv8g
 - test-a12dqjn5-1-197847055-fbpzvpkg
 - test-a12dqjn5-1-197847055-876xsmk8
 - test-a12dqjn5-1-197847055-xpt4xpcf
 - test-a12dqjn5-1-197847055-mqm69skq
 - test-a12dqjn5-1-197847055-5nggqqml
 - test-a12dqjn5-1-197847055-bswz6gbp
 - test-a12dqjn5-1-197847055-jh5jcxkh
 - test-a12dqjn5-1-197847055-zmgff7db
 - test-a12dqjn5-1-197847055-t654vdtc
 - test-a12dqjn5-1-197847055-9qvcfmm6
 - test-a12dqjn5-1-197847055-8kwgqj6c
 - test-a12dqjn5-1-197847055-v5vx7zr5
 - test-a12dqjn5-1-197847055-zbkw99fj
 - test-a12dqjn5-1-197847055-b92gvflf
 - test-a12dqjn5-1-197847055-6rf888n5
 - test-a12dqjn5-1-197847055-6djnt9vh
 - test-a12dqjn5-1-197847055-slr6lgjt
 - test-a12dqjn5-1-197847055-4l4vztch
 - test-a12dqjn5-1-197847055-qsq9t62j
 - test-a12dqjn5-1-197847055-4tczx56j
 - test-a12dqjn5-1-197847055-rhqpc8wz
 - test-a12dqjn5-1-197847055-2fr5rcf5
 - test-a12dqjn5-1-197847055-lzbss5gp
 - test-a12dqjn5-1-197847055-wjfq788t
 - test-a12dqjn5-1-197847055-l7gpn2zg
 - test-a12dqjn5-1-197847055-2vgqvplc
 - test-a12dqjn5-1-197847055-chhpqxb7
 - test-a12dqjn5-1-197847055-7dnqpbpx
 - test-a12dqjn5-1-197847055-c8pvpsfx
 - test-a12dqjn5-1-197847055-pcrkplf7
 - test-a12dqjn5-1-197847055-t6kvdzvr
 - test-a12dqjn5-1-197847055-lzq6g57m
 - test-a12dqjn5-1-197847055-d9pfqxh8
 - test-a12dqjn5-1-197847055-rfrcwc9c
 - test-a12dqjn5-1-197847055-x55bzjsv
 - test-a12dqjn5-1-197847055-cjxrtfhh
 - test-a12dqjn5-1-197847055-9p2ldbs6
 - test-a12dqjn5-1-197847055-hf6gg2gt
 - test-a12dqjn5-1-197847055-hb2mb497
 - test-a12dqjn5-1-197847055-p88srmdp
 - test-a12dqjn5-1-197847055-gv8sblw8
 - test-a12dqjn5-1-197847055-j7559tqq
 - test-a12dqjn5-1-197847055-cpkrtwrl
 - test-a12dqjn5-1-197847055-l9kvh5kw
 - test-a12dqjn5-1-197847055-zh2fsgl5
 - test-a12dqjn5-1-197847055-mprmdmh7
 - test-a12dqjn5-1-197847055-kntpvjc4
 - test-a12dqjn5-1-197847055-mqnkzs5h
 - test-a12dqjn5-1-197847055-7txn554p
 - test-a12dqjn5-1-197847055-2fmllvs5
 - test-a12dqjn5-1-197847055-slgkb52f
 - test-a12dqjn5-1-197847055-jgkkpdrq
 - test-a12dqjn5-1-197847055-rplw5ptb
 - test-a12dqjn5-1-197847055-jhddm4rj
 - test-a12dqjn5-1-197847055-r2djmvtt
 - test-a12dqjn5-1-197847055-8l54px7r
 - test-a12dqjn5-1-197847055-thvvjx59
 - test-a12dqjn5-1-197847055-f4pptmj2
 - test-a12dqjn5-1-197847055-57th7l5g
 - test-a12dqjn5-1-197847055-k99pvj2h
 - test-a12dqjn5-1-197847055-n8ltnwwr
 - test-a12dqjn5-1-197847055-t9npvp8l
 - test-a12dqjn5-1-197847055-55xxxcpl
 - test-a12dqjn5-1-197847055-9pdkkx8t
 - test-a12dqjn5-1-197847055-sr8nwdc4
 - test-a12dqjn5-1-197847055-8rk6mf26
 - test-a12dqjn5-1-197847055-fnr9tttr
 trials: 90
 trialsSucceeded: 90
```
