### ISSUE TITLE
Metricsformat doesn't work

### ISSUE THREAD

**Issue by VoVAllen** [kubeflow/katib#1679]
Hi,

I set the Metricsformat but it doesn't report the metrics.

Yaml setting
```yaml
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: objective
    additionalMetricNames:
      - ROCAUC
  ...
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
          - ([\w|-]+)\s*[:=]\s*((-?\d+)(\.\d+)?)
```

Output from metric collector
```
I0924 19:55:04.399879      14 main.go:136] Validation:
I0924 19:55:05.185063      14 main.go:136] objective: 0.083
I0924 19:55:05.185076      14 main.go:136] loss_avg: 0.083
I0924 19:55:05.185083      14 main.go:136] acc_avg: 0.979
```

Is there anything wrong in my setting?

**Comment by andreyvelich** [comment]
Thank you for creating this @VoVAllen.
You should specify the proper metric names and metrics format (check this example as a ref: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/file-metricscollector-example.yaml#L17).

```yaml
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: objective
    additionalMetricNames:
      - loss_avg
      - acc_avg
  ...
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
          - ([\\w|-]+)\\s*[:=]\\s*((-?\\d+)(\\.\\d+)?)
 ```
