### ISSUE TITLE
Metrics in scientific notation are not correctly parsed by default

### ISSUE THREAD

**Issue by fabianvdW** [kubeflow/katib#1702]
/kind bug

This is an excerpt of a Log of one Trial: As you can see the Score is still correct in file-metricscollector.go:49 but is then wrongly parsed somewhere:
```
I1007 08:08:59.928474      73 main.go:136] Score=-7.539458549707136e-05

7.10.2021 10:09:01 W1007 08:09:01.339500      73 file-metricscollector.go:49] Metrics will not have timestamp since Score=-7.539458549707136e-05 doesn't begin with timestamp string

7.10.2021 10:09:01 I1007 08:09:01.348925      73 main.go:397] Metrics reported. :

7.10.2021 10:09:01 metric_logs:<time_stamp:"0001-01-01T00:00:00Z" metric:<name:"Score" value:"-7.539458549707136" > >
```

**Comment by gaocegege** [comment]
Can you please show us the Experiment YAML too? Thanks for your help.

**Comment by fabianvdW** [comment]
Sure. I simplified the setup a bit:
Experiment yaml:
```
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: test
  namespace: kubeflow
spec:
  algorithm:
    algorithmName: bayesianoptimization
  maxFailedTrialCount: 10
  maxTrialCount: 100
  objective:
    goal: -3.32237
    objectiveMetricName: Score
    type: minimize
  parallelTrialCount: 10
  parameters:
  - feasibleSpace:
      max: '1.0'
      min: '0.0001'
    name: x0
    parameterType: double
  trialTemplate:
    primaryContainerName: katib-parameter-optimization
    retain: false
    trialParameters:
    - description: Parameter x0
      name: parameterX0
      reference: x0
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: 'false'
          spec:
            containers:
            - command:
              - python ./trial.py
              - --x0=${trialParameters.parameterX0}
              image: <redacted>
              name: katib-parameter-optimization
              resources:
                limits:
                  cpu: '1'
                  memory: 1G
                requests:
                  cpu: '1'
                  memory: 500M
            restartPolicy: Never

```
`trial.py`:
```
if __name__ == "__main__":
    print("Score=-7.539458549707136e-05")
```

**Comment by anencore94** [comment]
you may edit the metrics collector format to capture your format here

```yaml
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: file-metrics-collector
spec:
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
          - "write your pattern here"
    collector:
      kind: StdOut
```
