### ISSUE TITLE
start commond changed by webhook and cause worker pod failed

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/katib#1736]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
trial pod failed when the trialSpec is set as the following
```
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/pytorch-mnist:v1beta1-45c5727
                args:
                 - cd /code && python3 /code/pytorch_mnist.py --epochs=2 --log-path=/log/mnist.log --lr=${trialParameters.learningRate} --momentum=${trialParameters.momentum} --data_dir=/data
                command:
                  - /bin/bash
                  - -c
                imagePullPolicy: Always
                resources:
                  limits:
                    cpu: "7"
                    memory: 29Gi
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: 6125m
                    memory: 29Gi
                    nvidia.com/gpu: "1"
                volumeMounts:
                - mountPath: /data/
                  name: kubeflow-test-pvc
                  subPath: data/pytorch-mnist
                - mountPath: /code/
                  name: kubeflow-test-pvc
                  subPath: code/                  
                - mountPath: /dev/shm
                  name: dshm
            restartPolicy: Never
            imagePullSecrets:
            - name: default-secret  
            volumes:
            - name: kubeflow-test-pvc
              persistentVolumeClaim:
                claimName: kubeflow-test-pvc
            - emptyDir:
                medium: Memory
              name: dshm 
```
I check the job's args and commond in spec.containers 

```
      - args:
        - cd /code && python3 pytorch_mnist.py --epochs=2 --log-path=/log/mnist.log
          --lr=0.027190230182843826 --momentum=0.3976265101287227 --data_dir=/data
        command:
        - /bin/bash
        - -c

```
but the pod's args and commond in spec.containers  change like this
```
  - args:
    - /bin/bash -c cd /code && python3 pytorch_mnist.py --epochs=2 --log-path=/log/mnist.log
      --lr=0.027190230182843826 --momentum=0.3976265101287227 --data_dir=/data &&
      echo completed > /log/$$$$.pid
    command:
    - sh
    - -c

``` 
the error logs of pod 
```
python3: can't open file 'pytorch_mnist.py': [Errno 2] No such file or directory
```
It looks like katib webhook changed this value

**What did you expect to happen:**

Do not modify user settings with args and commond  in trialSpec

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Kubeflow version (`kfctl version`): 
- Minikube version (`minikube version`):
- Kubernetes version: (use `kubectl version`): 1.17
- OS (e.g. from `/etc/os-release`):

**Comment by gaocegege** [comment]
We have the webhook to support metrics collection, I think. I do not think we can remove it with the current design. WDYT @kubeflow/wg-automl-leads

**Comment by tingweiwu** [comment]
> We have the webhook to support metrics collection, I think. I do not think we can remove it with the current design. WDYT @kubeflow/wg-automl-leads

 is it possible to avoid modifying the user's start commond to support metrics  collection inject?

**Comment by gaocegege** [comment]
@andreyvelich Do you think it is possible?

**Comment by tingweiwu** [comment]
I modified metricsCollectorSpec refer to [custom-metrics-collector.yaml](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/metrics-collector/custom-metrics-collector.yaml)
```
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: "/katib/mnist.log"
        kind: File
    collector:
      kind: Custom
      customCollector:
        args:
          - -m
          - accuracy
          - -s
          - katib-db-manager.kubeflow:6789
          - -path
          - /katib/mnist.log
        image: kubeflowkatib/custom-metrics-collector:latest
        imagePullPolicy: Always
        name: custom-metrics-logger-and-collector
        env:
          - name: TrialNamePrefix
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
```
the work pod start cmd hasn't been changed，Maybe I could use this way.

additional 
1、when metric collector kind is StdOut,  is it better to change user's start cmd like 
```
 - args:
    - python3 /opt/mxnet-mnist/mnist.py --batch-size=64 --lr=0.018895820247895913
      --num-layers=4 --optimizer=ftrl 2>&1 | tee -i /var/log/katib/metrics.log;test ${PIPESTATUS[0]} -eq 0
    command:
    - sh
    - -c
```
rather than
```
 - args:
    - python3 /opt/mxnet-mnist/mnist.py --batch-size=64 --lr=0.018895820247895913
      --num-layers=4 --optimizer=ftrl 1>/var/log/katib/metrics.log 2>&1 && echo completed
      > /var/log/katib/$$$$.pid
    command:
    - sh
    - -c
```
because the first way keep trainning logs on StdOut, and I can get logs by kubectl logs -n kubeflow-test  $PODNAME training-container

2、If modify user's start commond is necessary when metrics collector type  is StdOut and File. Whether compound commands are kindly supported to run successfully.
e.g.
```
cd /code/ && python mnist.py
```
