### ISSUE TITLE
Support users to set more fields in suggetion deployment

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/katib#1737]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Is it possible to allow users to set more fields in suggetion deployment like we set the trailSpec
such as imagePullSecrets 、args、command and so on

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gaocegege** [comment]
I think it is a useful feature. WDYT @kubeflow/wg-automl-leads

**Comment by andreyvelich** [comment]
Thank you for creating this @tingweiwu!
We can allow to specify the Deployment `spec` or `spec.template.spec` in [Config Suggestion Settings](https://www.kubeflow.org/docs/components/katib/katib-config/#suggestion-settings), but then setting just Suggestion image will be more complicated for our users since they have to follow the correct API structure.
For example:
```json
"random": {
  "containers": [
    {
      "image": "docker.io/andreyvelichkevich/suggestion-chocolate:latest"
    }
  ]
 },
```

Does it look good to us @gaocegege @johnugeorge @tingweiwu ?

**Comment by tingweiwu** [comment]
It seems the [Suggestion settings](https://www.kubeflow.org/docs/components/katib/katib-config/#suggestion-settings) with configmap don't support `imagePullSecrets`  and other similar  spec settings in Deployment

It will be more flexible for user to set deployment attributes in algorithmSpec template
case 1: set imagePullSecrets and resource limits
```
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow-test
  name: job-test
spec:
    algorithm:
      algorithmName: random
      algorithmSpec:
        template:
          spec:
            containers:
            - image: docker.io/kubeflowkatib/suggestion-hyperopt:latest
              resources:
                limits:
                  cpu: 500m
                  ephemeral-storage: 5Gi
                  memory: 100Mi
                requests:
                  cpu: 50m
                  ephemeral-storage: 500Mi
                  memory: 10Mi 
            imagePullSecrets:
            - name: default-secret  
                 
```
case 2: set start commond and persistent volume,  as the new suggetion service may not build in image.
```
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow-test
  name: job-test
spec:
    algorithm:
      algorithmName: random
      algorithmSpec:
        template:
          spec:
            containers:
            - image: docker.io/kubeflowkatib/suggestion-new:latest
              args:
              - python /opt/apps/main.py 
              command:
              - /bin/bash
              - -c
              volumeMounts:
                - mountPath: /opt/apps
                  name: kubeflow-test-pvc
                  readOnly: true
            imagePullSecrets:
            - name: default-secret  
            volumes:
            - name: kubeflow-test-pvc
              persistentVolumeClaim:
                claimName: kubeflow-test-pvc

```
