### ISSUE TITLE
more flexiable with custom metric collector

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/katib#1739]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
I‘ve run this demo [custom-metrics-collector.yaml](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/metrics-collector/custom-metrics-collector.yaml)
```
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: "/katib/mnist.log"
        kind: File
    collector:
      kind: Custom
      customCollector:
        args:
          - -m
          - accuracy
          - -s
          - katib-db-manager.kubeflow:6789
          - -path
          - /katib/mnist.log
        image: kubeflowkatib/custom-metrics-collector:latest
        imagePullPolicy: Always
        name: custom-metrics-logger-and-collector
        env:
          - name: TrialNamePrefix
            valueFrom:
              fieldRef:
                fieldPath: metadata.name


```
and the worker pod created with webhook  will be mounted by  `emptyDir` to share the  logpath with metric contrainer

```
    volumeMounts:
    - mountPath: /katib
      name: metrics-volume
.....
  volumes:
  - emptyDir: {}
    name: metrics-volume

```
https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/pod/inject_webhook.go#L165

The `emptyDir` inject behavior achieve the purpose for collecting metric values, 
but if the user want to store the training container running log at the same time, he may not use `emptyDir` but other ersistent 
volume.
As an Custom Collector, is it better to be flexiable that allow the user to specify the log  `volumeMounts` in `metricsCollectorSpec`,
Thus user can define the metrics-volume with hostpath or nfs

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by tingweiwu** [comment]
solved by remove source from `spec.metricsCollectorSpec` and add `volumeMounts:` in  `spec.metricsCollectorSpec.customCollector`
```
    source:
      fileSystemPath:
        path: "/log/mnist.log"
        kind: File

```
e.g.:
````
 metricsCollectorSpec:
    collector:
      kind: Custom
      customCollector:
        args:
          - -t
          - $(TrialNamePrefix)
          - -m
          - accuracy
          - -o-type
          - maximize
          - -s-db
          - katib-db-manager.kubeflow:6789
          - -path
          - /log/mnist.log
          - -f
          - '{metricName: ([\w|-]+), metricValue: ((-?\d+)(\.\d+)?)}'
        image: kubeflowkatib/custom-metrics-collector:latest
        imagePullPolicy: IfNotPresent
        name: logger-and-collector
        env:
          - name: TrialNamePrefix
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['job-name']
        volumeMounts:
           - mountPath: /log/
             name: kubeflow-test-pvc
             subPath: kubeflow-test/log/

```
