### ISSUE TITLE
use the model store in local pvc

### ISSUE THREAD

**Issue by wallacezzzzz007** [kubeflow/katib#1742]
I saw a lots of examples are using the docker image of models, can we use the model in our local pvc?
For example, if I create a pvc named `katib`, and then move the model and dataset to the `/mnt` in katib'pod, can we directly use the model like `modelUri: pvc://katib` or other way?

**Comment by gaocegege** [comment]
You need to provide the model training script instead of the model weights and structure. Do you mean you want to put the training script in a volume?

**Comment by wallacezzzzz007** [comment]
> You need to provide the model training script instead of the model weights and structure. Do you mean you want to put the training script in a volume?

yes

**Comment by gaocegege** [comment]
Yes, you can but actually, the training script is not a huge file. I am not sure why you need it. Could you please explain your use scenario?

**Comment by wallacezzzzz007** [comment]
Yes, trainiing script itself is not huge, but when we facing a large dataset, if we put the dataset in the image, that could be huge. (maybe there is other way to deal with the large data, plz tell me thx) And also, I use the kubeflow-notebook to clean the original dataset and build the base model, since the notebook is inside of kubeflow (inside of a pod maybe), is hard to build a docker image directly in the notebook (thats my opinion, if im wrong, plz fix it). So, thats why i wanna dictly send the training script and the dataset to the volume. But if there is a better way, plz tell me.
thank you

**Comment by gaocegege** [comment]
Oh got it. Of course, you can place the dataset in a volume.

cc @kubeflow/wg-automl-leads Do you have better ideas in this scenario?

**Comment by wallacezzzzz007** [comment]
thanks for ur help @gaocegege 
So, for example i use this [yaml file](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-template/trial-metadata-substitution.yaml), and i send the training script to `/mnt/model/model.py`, wether i only need to change the containers information like:
Here is the original one:
```
        template:
          spec:
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/mxnet-mnist:v1beta1-45c5727
                command:
                  - "python3"
                  - "/opt/mxnet-mnist/mnist.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                env:
                  - name: TRIAL_NAME
                    value: ${trialParameters.trialName}
```
Change to:
```
        template:
          spec:
            containers:
              - name: training-container
                modelUri: pvc://katib
                command:
                  - "python3"
                  - "/mnt/model/model.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                env:
                  - name: TRIAL_NAME
                    value: ${trialParameters.trialName}
```
Thanks a lot
