### ISSUE TITLE
blocked with failureCondition when use pod resource as a trial template

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/katib#1748]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
I Modify Katib controller Deployment’s args with the new flag `    - "--trial-resources=Pod.v1."`
and create experiment with the following trial
```
....
 trialTemplate:
    failureCondition: 'status.phase=="FAILED"'
    #successCondition: '(status.phase=="Succeeded")#'
    successCondition: 'status.conditions.#(type=="Ready")#|#(reason=="PodCompleted")#'
    primaryContainerName: train
    trialParameters:
      - name: learningRate
        description: Learning rate for the train model
        reference: lr
      - name: momentum
        description: Momentum for the train model
        reference: momentum
    trialSpec:
      apiVersion: v1
      kind: Pod
      spec:

....
```
I want to get the trial worker’s object status through this field `status.phase=="Succeeded"` for the first time, but when I look into the https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/trial/util/job_util.go, I found it don't works
```
     // Try to get success condition using spec.successCondition expression
	successJobCondition := gjson.Get(deployedJobJSON, trial.Spec.SuccessCondition)

	// The same logic as for failure condition
	if successJobCondition.IsObject() || (successJobCondition.IsArray() && len(successJobCondition.Array()) > 0) {
		strCondition := successJobCondition.String()
```
I change to this field`status.conditions.#(type=="Ready")#|#(reason=="PodCompleted")#` and it works 
but I'am blocked with the failureCondition,because the conditions is the same when pod phase is `Failed` and `Pending`

```
 "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2021-11-26T10:19:38Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2021-11-26T10:19:53Z",
                "message": "containers with unready status: [train metric-collector]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2021-11-26T10:19:53Z",
                "message": "containers with unready status: [train metric-collector]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2021-11-26T10:19:38Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "phase": "Failed"
```

```
 "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2021-11-26T10:27:03Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2021-11-26T10:27:03Z",
                "message": "containers with unready status: [train]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2021-11-26T10:27:03Z",
                "message": "containers with unready status: [train]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2021-11-26T10:27:03Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "phase": "Pending",
....
```

is is better to set  failureCondition  and successCondition  with two fields,one field declare the json path and the second declare the expected value.
e.g.
For Kubernetes Job,  
successCondition：  the json path is  `status.conditions.#(type==\"Complete\").status`  and expected value is `True`
failureCondition： the json path is  `status.conditions.#(type==\"Failed\").status`  and expected value is `True`

For Kubernetes Pod
successCondition：  the json path is  `status.phase`  and expected value is `Succeeded`
failureCondition： the json path is  `status.phase`  and expected value is `Failed`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
