### ISSUE TITLE
error when creating "tfjob-example.yaml": admission webhook "validator.experiment.katib.kubeflow.org" denied the reques

### ISSUE THREAD

**Issue by mgiessing** [kubeflow/katib#1800]
/kind bug

**What steps did you take and what happened:**
Downloaded the `tfjob` example from branch v0.12.0 adjusted it to my user namespace, added section to remove  applied it and got this error:

```
$ kubectl apply -f tfjob-example.yaml 
Error from server: error when creating "tfjob-example.yaml": admission webhook "validator.experiment.katib.kubeflow.org" denied the request: unable to get Suggestion config data for algorithm random: invalid character '}' looking for beginning of object key string
```

**What did you expect to happen:**
I'd expect that the job will be created 

**Anything else you would like to add:**

Katbi seems to be running:

```
$ oc get pods | grep katib
katib-controller-6756b96cb6-hvghw                            1/1     Running   0          12m
katib-db-manager-8679f4d559-9rtrv                            1/1     Running   0          12m
katib-mysql-55c6c4ff77-rvcvb                                 1/1     Running   0          12m
katib-ui-85fc94897c-phfl7                                    1/1     Running   0          12m
```

tfjob-example:

```
apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: kubeflow-user-example-com
  name: tfjob-example
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy_1
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: /train
        kind: Directory
    collector:
      kind: TensorFlowEvent
  parameters:
    - name: learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: batch_size
      parameterType: int
      feasibleSpace:
        min: "100"
        max: "200"
  trialTemplate:
    primaryContainerName: tensorflow
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: learning_rate
      - name: batchSize
        description: Batch Size
        reference: batch_size
    trialSpec:
      apiVersion: "kubeflow.org/v1"
      kind: TFJob
      spec:
        tfReplicaSpecs:
          Worker:
            replicas: 2
            restartPolicy: OnFailure
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: "false"
              spec:
                containers:
                  - name: tensorflow
                    image: quay.io/mgiessing/tf-mnist-with-summaries:1.0
                    command:
                      - "python"
                      - "/var/tf_mnist/mnist_with_summaries.py"
                      - "--log_dir=/train/metrics"
                      - "--learning_rate=${trialParameters.learningRate}"
                      - "--batch_size=${trialParameters.batchSize}"
```

**Environment:**

- Katib version (check the Katib controller image version): `v0.12.0`
- Kubernetes version: (`kubectl version`): `v1.19.9` (Here I'm using vanilla k8s, but this error does also occur on OCP)
- OS (`uname -a`): `Linux node1 4.18.0-348.el8.ppc64le #1 SMP Tue Dec 28 13:22:13 UTC 2021 ppc64le ppc64le ppc64le GNU/Linux
`

If you need any more logs from controller etc. let me know!

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍
