### ISSUE TITLE
Webhook mutation and validation is not sending pod events back to Katib controller on OCP 4.8+

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/katib#1803]
/kind feature

**Describe the solution you'd like**
When deploying Kubeflow 1.4 with Openshift overlays, the Katib webhook mutation and validation is not sending any pod events to the Katib controller. So the metrics collectors are not injected to the trial worker pods. This makes the Trial keep running forever despite the tfjob is finished.

It could be related to https://github.com/kubeflow/katib/issues/1512, but we don't have any issue with ca certificates and there are no errors inside the controller. But we realized there are no pod events sending back to Katib despite the mutation webhook is matching to our user namespace.

@maanur Are you aware of any new OCP changes in the new OpenShift version recently? Thanks. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by maanur** [comment]
There's a common practice of setting NetworkPolicies that disable inter-namespace communications. Most likely, you are facing that setup.

Try adding these NetworkPolicies to controller's namespace:
```yaml
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-webhooks
  namespace: kubeflow
spec:
  podSelector:
    matchLabels:
      katib.kubeflow.org/component: controller
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
  policyTypes:
    - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-db-manager-from-trials
  namespace: kubeflow
spec:
  podSelector:
    matchLabels:
      katib.kubeflow.org/component: db-manager
  ingress:
    - ports:
        - protocol: TCP
          port: 6789
      from:
        - namespaceSelector:
            matchLabels:
              katib.kubeflow.org/metrics-collector-injection: enabled
  policyTypes:
    - Ingress
```
And another one to the "user" namespace (where Experiments are to be created):
```yaml
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-katib-suggestion-from-controller
  namespace: userspace
spec:
  podSelector:
    matchExpressions:
      - key: katib.kubeflow.org/suggestion
        operator: Exists
  ingress:
    - ports:
        - protocol: TCP
          port: 6789
      from:
        - podSelector:
            matchLabels:
              katib.kubeflow.org/component: controller
  policyTypes:
    - Ingress
```
