### ISSUE TITLE
Experiment stuck due to hitting `Suggestion` custom resource size limits

### ISSUE THREAD

**Issue by nielsmeima** [kubeflow/katib#1847]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Submitting a large (i.e. resulting in a large number of trials, in this case ~14500 with 4 hyperparameters with 10/11 values per hyperparameter) experiment results in the `Suggestion` custom resource reaching the size limits of custom resources dictated by Kubernetes due to all suggestions being stored in this resource. This results in the following error being output by the Katib controller when trying to update the Suggestion custom resource: `Request entity too large` and the experiment not being able to progress. [This](https://stackoverflow.com/questions/61754857/request-entity-too-large-limit-is-3145728-when-trying-to-update-a-k8s-cr-reso) issue seems to describe the exact problem.

Argo Workflows seems to have encountered the same problem, described [here](https://github.com/argoproj/argo-workflows/issues/3738) and solved it by allowing for 1) compression of the data stored in the status field of the custom resource and 2) storage of information under the status field in a relational database as described [here](https://argoproj.github.io/argo-workflows/offloading-large-workflows/).

**What did you expect to happen:**
I expected Katib to be able to handle search spaces or arbitrary size.

**Anything else you would like to add:**
A workaround would be to manually split the experiment into smaller subexperiments to circumvent the size limits of custom resources. Ideally, this is solved by following a similar approach as Argo does for their Workflow custom resources.

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by johnugeorge** [comment]
Thanks for creating this issue.  Can you provide more info about the experiment yaml and other relevant information for reproducibility? 

MaxTrials - 14500 
Parameter1, Parameter2, Parameter3, Parameter4 - 11 values each
ParallelTrials - ?

**Comment by nielsmeima** [comment]
Yes, please see below for the experiment `yaml` as well as the other dependencies to be able to reproduce the experiment. I create a configmap `k create configmap script --from-file=run.py=run.py` based on a `run.py` file to mock my actual implementation (but this also results in the same issues). The configmap then gets mounted in the main container of the experiment taking in the parameters and producing a value for the objective of interest. I have also attached the `run.py` file below.

`Experiment`
```yaml
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: debug
spec:
  objective:
    type: maximize
    goal: 500
    objectiveMetricName: cost
  algorithm:
    algorithmName: grid
  parallelTrialCount: 20
  maxTrialCount: 14641
  maxFailedTrialCount: 2000
  parameters:
    - name: a
      parameterType: double
      feasibleSpace:
        min: "1.30"
        max: "1.41"
        step: "0.01"
    - name: b
      parameterType: categorical
      feasibleSpace:
        list: ["0.0010", "0.0025", "0.0063", "0.0158", "0.0398", "0.1000", "0.2512", "0.6310", "1.5849", "3.9811", "10.0000"]
    - name: c
      parameterType: double
      feasibleSpace:
        min: "1.30"
        max: "1.41"
        step: "0.01"
    - name: d
      parameterType: categorical
      feasibleSpace:
        list: ["0.0010", "0.0025", "0.0063", "0.0158", "0.0398", "0.1000", "0.2512", "0.6310", "1.5849", "3.9811", "10.0000"]
  trialTemplate:
    retain: false
    primaryContainerName: training-container
    trialParameters:
      - name: a
        reference: a
        description: ""
      - name: b
        reference: b
        description: ""
      - name: c 
        reference: c
        description: ""
      - name: d 
        reference: d
        description: ""
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: docker.io/python:alpine3.15
                volumeMounts:
                - name: script
                  mountPath: /app/run.py
                  subPath: run.py
                command:
                  - "python3"
                  - "/app/run.py"
                  - "${trialParameters.a}"
                  - "${trialParameters.b}"
                  - "${trialParameters.c}"
                  - "${trialParameters.d}"
            restartPolicy: Never
            volumes:
              - name: script
                configMap:
                  name: script
```
The mock implementation `run.py`
```python
import sys
import time
time.sleep(4)
cost = sum([float(x) for x in sys.argv[1:]])
print(f"cost={cost}")
```
