### ISSUE TITLE
metricStrategies doesn't seem to work correctly

### ISSUE THREAD

**Issue by spatre** [kubeflow/katib#1876]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I ran an experiment(random.yaml) with the below metricStrategies. I basically used "latest" value for both Validation-accuracy and Train-accuracy under **metricStrategies**.
<img width="598" alt="image" src="https://user-images.githubusercontent.com/25424489/170597487-e0e0fba0-0ad9-4f47-8ed2-194e53c148aa.png">
When the experiment completed, It was only taking the "max" value from each trial for both Validation-accuracy and Train-accuracy. Then computes the maximum value from those for the Best Trail performance. 

**What did you expect to happen:**
I had expected it to take the **latest** value from each trial for both Validation-accuracy and Train-accuracy. Then compute the maximum value from those to get the Best Trial Performance as explained in the documentation.
<img width="962" alt="image" src="https://user-images.githubusercontent.com/25424489/170599568-07e8253f-d55c-49ab-a41b-21a3a9a81269.png">

To elaborate a bit, consider the below graph. The latest Validation-accuracy is **93.5**, but it considers the maximum value from that trial and outputs **94.068**
<img width="730" alt="image" src="https://user-images.githubusercontent.com/25424489/170601946-0d7dcc47-e38c-46a1-89a2-68d7ae5435e7.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/25424489/170602297-5bc82841-b4dc-4343-92e1-379774db52bd.png">

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
It also didn't work when I chose "min" as the metricStrategies value for both Validation-accuracy and Train-accuracy. It would basically pick the maximum value from each trial and then choose the maximum value among that to display as the Best Trial Performance. Am I missing something? 

The complete random.yaml file that I used.
```
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: random
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
    - Train-accuracy
    metricStrategies:
    - name: Validation-accuracy
      value: latest
    - name: Train-accuracy
      value: latest
  algorithm:
    algorithmName: tpe
  parallelTrialCount: 6
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: num-layers
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "5"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - sgd
          - adam
          - ftrl
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: numberLayers
        description: Number of training model layers
        reference: num-layers
      - name: optimizer
        description: Training model optimizer (sdg, adam or ftrl)
        reference: optimizer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/mxnet-mnist:latest
                command:
                  - "python3"
                  - "/opt/mxnet-mnist/mnist.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                  - "--num-layers=${trialParameters.numberLayers}"
                  - "--optimizer=${trialParameters.optimizer}"
                resources:
                  limits:
                    nvidia.com/gpu: 1
            restartPolicy: Never
```

**Environment:**

- Katib version (check the Katib controller image version):
`kubectl apply -k "github.com/kubeflow/katib.git/manifests/v1beta1/installs/katib-standalone?ref=master"`
I am using the latest Katib version.

- Kubernetes version: (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"c999fea1e6dbf111d64000dfaaff45edaa4c34d2", GitTreeState:"clean", BuildDate:"2022-01-11T12:16:14Z", GoVersion:"go1.16.12 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (`uname -a`):
`5.13.0-1021-oracle #26~20.04.1-Ubuntu SMP Mon Mar 7 14:26:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍
