### ISSUE TITLE
A metrics collector for Kubeflow Pipeline Metrics artifacts

### ISSUE THREAD

**Issue by votti** [kubeflow/katib#2019]
/kind feature

**Describe the solution you'd like**
Currently a aim is to do parameter tuning over pipelines in katib (#1914, #1993).

Kubeflow pipelines allow for dedicated metrics artifacts:
https://kubeflow-pipelines.readthedocs.io/en/master/source/dsl.html?h=metrics#kfp.dsl.Metrics
https://www.kubeflow.org/docs/components/pipelines/v1/sdk/pipelines-metrics/

Having a dedicated[ Katib sidecar metrics collector](https://www.kubeflow.org/docs/components/katib/experiment/#metrics-collector) that collects the metrics from this artifacts, would make pipelines and katib work together quite nicely.

The current workaround is to use the stdout collector, but this causes issues with the complex commands in pipeline components (#1914, will add dedicated issue soon).

**Anything else you would like to add:**
-

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by votti** [comment]
I think I may give this a go - I would try to build this in Python analogous to the [tfevent-metricscollector](https://github.com/kubeflow/katib/tree/master/pkg/metricscollector/v1beta1/tfevent-metricscollector).
Does this sound like a reasonable approach? I am also happy for any other suggestion.

**Comment by AlexandreBrown** [comment]
@votti Hello, did you have the chance to give it a try?

**Comment by votti** [comment]
Small update: 
I have now a metrics collector for kubeflow v1 pipelines that I think should work (modeled after [tfevent-metricscollector](https://github.com/kubeflow/katib/tree/master/pkg/metricscollector/v1beta1/tfevent-metricscollector)).

What I am failing is to pass the trial name to the custom connector.
Essentially I am using the a very similar configuration as in the custom connector example here:
[tfevent-metricscollector](https://github.com/kubeflow/katib/tree/master/pkg/metricscollector/v1beta1/tfevent-metricscollector).

My cli metricscollector takes an argument "-t" or "--trial_name" with the trial name to use for reporting (exactly as the tfevent-metricscollector).
Would maybe someone know a hint how to configure this such that the current trial-name would be passed as arg?

**Comment by votti** [comment]
I am now really a bit confused:
Reading the source code of the metrics collector sidecar injection `inject_webhook`, it looks to me as if the trial name should be actually added to the args: 
https://github.com/kubeflow/katib/blob/22b740802a06d8926255b204076837d6e344ebb9/pkg/webhook/v1beta1/pod/inject_webhook.go#L302

Yet looking at the pods Katib creates, all these arguments seem to be missing.
Is there anything I do not see?

My current section to specify the metrics collector:

```
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: "/tmp/outputs/mlpipeline_metrics/data"
        kind: File
    collector:
      customCollector:
        args: []
        image: votti/kfpv1-metricscollector:v0.0.7
        imagePullPolicy: Always
        name: custom-metrics-logger-and-collector
      kind: Custom
 ```
 
 Which creates a specification as:
 ```
  - image: votti/kfpv1-metricscollector:v0.0.7
    imagePullPolicy: Always
    name: custom-metrics-logger-and-collector
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/outputs/mlpipeline_metrics
      name: metrics-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnmkw
      readOnly: true
```
