### ISSUE TITLE
Arguments missing for custom metrics collector

### ISSUE THREAD

**Issue by votti** [kubeflow/katib#2109]
/kind bug

**What steps did you take and what happened:**
I want to run an experiment with a custom metrics collector using the following spec:

```
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: "/tmp/outputs/mlpipeline_metrics/data"
        kind: File
    collector:
      customCollector:
        image: votti/kfpv1-metricscollector:v0.0.7
        imagePullPolicy: Always
        name: custom-metrics-logger-and-collector
      kind: Custom
```

This is used for: #2019

**What did you expect to happen:**
I expected the metrics collector sidecar pod to be created to carry the arguments:
- `-t`  trial.Name
- `-m`:  metricNames
- `-o-type`:  string(trial.Spec.Objective.Type)
- `-s-db`:  katibmanagerv1beta1.GetDBManagerAddr()

which should have been added by the following code:
https://github.com/kubeflow/katib/blob/0a7453d212ab751e5f9cc12a834e7aa634cbf2ff/pkg/webhook/v1beta1/pod/inject_webhook.go#L298

**Anything else you would like to add:**
-

**Environment:**

- Katib version (check the Katib controller image version): docker.io/kubeflowkatib/katib-controller:v0.14.0"
- Kubernetes version: (`kubectl version`): 
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.23.14-gke.1800
- OS (`uname -a`): Linux LAPTOP-SS9UALAT 4.19.128-microsoft-standard  SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by andreyvelich** [comment]
Thank you for creating this @votti!

I think, originally we didn't modify Custom Metrics Collector container args.
To send Trial names for such cases, you can check this example: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/metrics-collector/custom-metrics-collector.yaml#L32-L36.

Does it solve your problem ? Or you want to pass some other info to your container ?

**Comment by votti** [comment]
Ok let me try this again - I thought `TrialNamePrefix` from `metadata.name` was just the prefix of the trial, but not the actual `trial_name`.

I need the trial name to submit the metrics to the correct `trial_name` such that it is correctly registered:             
https://github.com/d-one/katib/blob/0d25cbfc6a69e3014c3c25c9ea94b4c97b965473/cmd/metricscollector/v1beta1/kfpv1-metricscollector/main.py#L109

I wonder how the kubeflowkatib/custom-metrics-collector:latest managed to do this - but i guess that code is still lost: https://github.com/kubeflow/katib/issues/1263

Once I get this working, I think I have the know-how together to make a new `custom-metrics-collector` example that should simplify any future development of such a collector.

**Comment by votti** [comment]
Actually this works and gives the `TrialName`:
```
  metricsCollectorSpec:
    collector:
      customCollector:
        args:
          - -m
          - val-accuracy;accuracy
          - -s
          - katib-db-manager.kubeflow:6789
          - -path
          - /tmp/outputs/mlpipeline_metrics/data
          **- -t
          - $(TrialNamePrefix)**
        image: votti/kfpv1-metricscollector:v0.0.9
        imagePullPolicy: Always
        name: custom-metrics-logger-and-collector
        env:
          - name: TrialNamePrefix
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      kind: Custom
    source:
      fileSystemPath:
        kind: File
        path: /tmp/outputs/mlpipeline_metrics/data
```

Thanks for pointing me to this!
