### ISSUE TITLE
Experiment with Argo Workflow fails to collect reported metrics

### ISSUE THREAD

**Issue by pedrovgp** [kubeflow/katib#2143]
/kind bug

**What steps did you take and what happened:**
I created an Experiment with Argo Workflow as trialSpec. A minimal reproducible example of the Experiment yaml is below, along with the picture of the results. The trials do report the metrics (the logs of "metrics-and-logger-collector" container says so). The trial appear as `Succeeded` in the UI, but no metrics are shown and new trials are not created.

The problem seems to happen any time the task that logs the metrics is not the last to finish.

```yaml
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  generateName: testkat-
spec:
  algorithm:
    algorithmName: random
  maxFailedTrialCount: 8
  maxTrialCount: 10
  objective:
    additionalMetricNames:
    - roc-auc-score
    goal: 0.99
    objectiveMetricName: average-precision-score
    type: maximize
  parallelTrialCount: 3
  parameters:
  - name: lr
    parameterType: double
    feasibleSpace:
      min: "0.01"
      max: "0.03"
  - name: num_estimators
    parameterType: int
    feasibleSpace:
      min: "50"
      max: "500"
  trialTemplate:
    failureCondition: status.[@this].#(phase=="Failed")#
    primaryContainerName: main
    retain: true
    successCondition: status.[@this].#(phase=="Succeeded")#
    trialParameters:
    - name: learningRate
      description: Learning rate for the training model
      reference: lr
    - description: Name of the current trial's job
      name: trialName
      reference: ${trialSpec.Name}
    - description: ''
      name: num_estimators
      reference: num_estimators
    trialSpec:
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      metadata:
        # Required
        labels:
          workflows.argoproj.io/controller-instanceid: hyper-opt-argo-controller
      spec:
        entrypoint: dag
        serviceAccountName: pipeline-runner
        templates:
        - name: model-training
          metadata:
            annotations:
              # Required
              sidecar.istio.io/inject: 'false'
          container:
            name: model-training
            image: docker.io/kubeflowkatib/mxnet-mnist:latest
            command:
              - "echo"
            args:
            - "--lr=${trialParameters.learningRate}"
            - "--num_estimators=${trialParameters.num_estimators}"
            - "--trialName=${trialParameters.trialName}"
            - "roc-auc-score=0.53"
            - "average-precision-score=0.55"

        - name: model-training-2
          metadata:
            annotations:
              # Required
              sidecar.istio.io/inject: 'false'
          container:
            name: model-training-2
            image: docker.io/kubeflowkatib/mxnet-mnist:latest
            command:
            - "echo"
            args:
            - "Second task, does not do anything"
        - name: dag
          dag:
            tasks:
            - dependencies:
                - model-training-job
              name: model-training-2-job
              template: model-training-2
            - dependencies: []
              name: model-training-job
              template: model-training
          
```
Final result:
![image](https://user-images.githubusercontent.com/2333868/229932220-fdf9c5b4-3222-454f-8dc0-a579374feebb.png)

**What did you expect to happen:**

The metrics to show up in the UI and new trials to be created.

**Environment:**

- Katib version:
image: docker.io/kubeflowkatib/katib-controller:v1beta1-a96ff59)

- Kubernetes version: (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"archive", BuildDate:"2022-05-23T12:47:54Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-48e63af", GitCommit:"8ff984ddd00ccb2ccbf5043a71ce10865e2bcef4", GitTreeState:"clean", BuildDate:"2023-01-24T09:30:48Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (`uname -a`):
Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64

- argo controller:
image: quay.io/argoproj/workflow-controller:v3.4.5
---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍
