### ISSUE TITLE
katib use crd as tail template

### ISSUE THREAD

**Issue by Jerry-yz** [kubeflow/katib#2327]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
i follow this [guide](https://www.kubeflow.org/docs/components/katib/trial-template/#use-custom-kubernetes-resource-as-a-trial-template)
but i add deployment katib-controller  args --trial-resources=PipelineRun.v1beta1.tekton.dev
pod can not start, error info:
`
flag provided but not defined: -trial-resources
Usage of ./katib-controller:
  -katib-config string
        The katib-controller will load its initial configuration from this file. Omit this flag to use the default configuration values.
  -kubeconfig string
        Paths to a kubeconfig. Only required if out-of-cluster
`
**What did you expect to happen:**
how i fix it
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Katib version (check the Katib controller image version): 
- Kubernetes version: (`kubectl version`):
- OS (`uname -a`):

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by tenzen-y** [comment]
Thank you for creating this issue. Actually, we removed the option from the katib-controller.
Also, we recently updated the documentation. So, could you re-check the documentation?
Thanks.

**Comment by Jerry-yz** [comment]
> Thank you for creating this issue. Actually, we removed the option from the katib-controller. Also, we recently updated the documentation. So, could you re-check the documentation? Thanks.

thanks, i have other question
https://github.com/kubeflow/katib/blob/fc858d15dd41ff69166a2020efa200199063f9ba/manifests/v1beta1/installs/katib-standalone/katib-config.yaml#L9-L15
this file is a crd in k8s?

**Comment by tenzen-y** [comment]
> > Thank you for creating this issue. Actually, we removed the option from the katib-controller. Also, we recently updated the documentation. So, could you re-check the documentation? Thanks.
> 
> thanks, i have other question
> 
> https://github.com/kubeflow/katib/blob/fc858d15dd41ff69166a2020efa200199063f9ba/manifests/v1beta1/installs/katib-standalone/katib-config.yaml#L9-L15
> 
> 
> this file is a crd in k8s?

The `katib-config.yaml` is not CRD. That is embedded in configMap here: https://github.com/kubeflow/katib/blob/fc858d15dd41ff69166a2020efa200199063f9ba/manifests/v1beta1/installs/katib-standalone/kustomization.yaml#L30-L36

**Comment by Jerry-yz** [comment]
> > > Thank you for creating this issue. Actually, we removed the option from the katib-controller. Also, we recently updated the documentation. So, could you re-check the documentation? Thanks.
> > 
> > 
> > thanks, i have other question
> > https://github.com/kubeflow/katib/blob/fc858d15dd41ff69166a2020efa200199063f9ba/manifests/v1beta1/installs/katib-standalone/katib-config.yaml#L9-L15
> > 
> > this file is a crd in k8s?
> 
> The `katib-config.yaml` is not CRD. That is embedded in configMap here:
> 
> https://github.com/kubeflow/katib/blob/fc858d15dd41ff69166a2020efa200199063f9ba/manifests/v1beta1/installs/katib-standalone/kustomization.yaml#L30-L36

the yaml file kind filed is katib-config, whether it should equal configMap

**Comment by tenzen-y** [comment]
Yes, that is configMap. The installation command builds the configMap below:

```yaml
apiVersion: v1
data:
  katib-config.yaml: |
    ---
    apiVersion: config.kubeflow.org/v1beta1
    kind: KatibConfig
    init:
      certGenerator:
        enable: true
      controller:
        webhookPort: 8443
        trialResources:
          - Job.v1.batch
          - TFJob.v1.kubeflow.org
          - PyTorchJob.v1.kubeflow.org
          - MPIJob.v1.kubeflow.org
          - XGBoostJob.v1.kubeflow.org
          - MXJob.v1.kubeflow.org
    runtime:
      metricsCollectors:
        - kind: StdOut
          image: docker.io/kubeflowkatib/file-metrics-collector:latest
        - kind: File
          image: docker.io/kubeflowkatib/file-metrics-collector:latest
        - kind: TensorFlowEvent
          image: docker.io/kubeflowkatib/tfevent-metrics-collector:latest
          resources:
            limits:
              memory: 1Gi
      suggestions:
        - algorithmName: random
          image: docker.io/kubeflowkatib/suggestion-hyperopt:latest
        - algorithmName: tpe
          image: docker.io/kubeflowkatib/suggestion-hyperopt:latest
        - algorithmName: grid
          image: docker.io/kubeflowkatib/suggestion-optuna:latest
        - algorithmName: hyperband
          image: docker.io/kubeflowkatib/suggestion-hyperband:latest
        - algorithmName: bayesianoptimization
          image: docker.io/kubeflowkatib/suggestion-skopt:latest
        - algorithmName: cmaes
          image: docker.io/kubeflowkatib/suggestion-goptuna:latest
        - algorithmName: sobol
          image: docker.io/kubeflowkatib/suggestion-goptuna:latest
        - algorithmName: multivariate-tpe
          image: docker.io/kubeflowkatib/suggestion-optuna:latest
        - algorithmName: enas
          image: docker.io/kubeflowkatib/suggestion-enas:latest
          resources:
            limits:
              memory: 400Mi
        - algorithmName: darts
          image: docker.io/kubeflowkatib/suggestion-darts:latest
        - algorithmName: pbt
          image: docker.io/kubeflowkatib/suggestion-pbt:latest
          persistentVolumeClaimSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 5Gi
      earlyStoppings:
        - algorithmName: medianstop
          image: docker.io/kubeflowkatib/earlystopping-medianstop:latest
kind: ConfigMap
metadata:
  name: katib-config
  namespace: kubeflow
```
