### ISSUE TITLE
if experiment name is too long the suggestion service can't start

### ISSUE THREAD

**Issue by garymm** [kubeflow/katib#2454]
### What happened?

I provided an experiment name that was 57 characters long.
It got stuck waiting for trials to be created because the suggestion service couldn't be started because the name was more than 63 characters long.

### What did you expect to happen?

Katib to pick a valid name for the service.

### Environment

Kubernetes version:
```bash
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
```

Katib controller version:
```bash
$ kubectl get pods -n kubeflow -l katib.kubeflow.org/component=controller -o jsonpath="{.items[*].spec.containers[*].image}"
docker.io/kubeflowkatib/katib-controller:v0.17.0
```

Katib Python SDK version:
```bash
$ pip show kubeflow-katib
Name: kubeflow-katib
Version: 0.17.0
```

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍

**Comment by garymm** [comment]
I may be interested in contributing a fix if it would be welcome and some guidance could be provided as to how to go about it.

**Comment by andreyvelich** [comment]
Thank you for creating this @garymm!
Yes, it's a great idea, we can just add the Experiment validation here: https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/experiment/validator/validator.go#L81

/assign @garymm 

Feel free to reach out if you have any questions.

**Comment by garymm** [comment]
What exactly should the validaton be though? I think the better fix is to name the experiment service in a way that is guaranteed to be legal. Where might that happen in the code?

**Comment by andreyvelich** [comment]
@garymm Our longest algorithm name is: bayesianoptimization and the Suggestion's Deployment name is <Experiment_name>-<Algorithm_Name>.
So I suggest that we validate that Experiment name is no longer than 40 symbols just to be safe.

You just simple need to add this additional check here: https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/experiment/validator/validator.go#L85

E.g. `|| len(instance.name) > 40`.

**Comment by AydanPirani** [comment]
Hello! @andreyvelich has a PR been made to fix this issue? If not, I would be open to helping out as well :)

**Comment by garymm** [comment]
There are no PRs open that reference this issue.

**Comment by andreyvelich** [comment]
@AydanPirani Yes, please feel free to submit a PR
/assign @AydanPirani

**Comment by AydanPirani** [comment]
Sorry for the delay, will get this up and going ASAP :)

**Comment by AydanPirani** [comment]
Hi @garymm (cc @andreyvelich)! I'm trying to reproduce this locally, and I had a few questions:

1. What command did you run to get Katib version? I get the following when I run the command you included:

```
kubectl get pods -n kubeflow -l katib.kubeflow.org/component=controller -o jsonpath="{.items[*].spec.containers[*].image}"

docker.io/kubeflowkatib/katib-controller:v0.17.0
docker.io/kubeflowkatib/katib-controller:latest
zsh: no such file or directory: docker.io/kubeflowkatib/katib-controller:v0.17.0`

```

2. Is there anything specific you did to run the experiment? A link to the yaml file would be nice, so I can also see the same results on my end :)

Thanks!

**Comment by garymm** [comment]
I ran:

```
kubectl get pods -n kubeflow -l katib.kubeflow.org/component=controller -o jsonpath="{.items[*].spec.containers[*].image}"
```

Just create an experiment with a long name, such that experiment name + algorithm name > 63 characters.

**Comment by andreyvelich** [comment]
@garymm Is right, this command prints the version of Katib controller which is equal to Katib version (e.g. v0.17.0).
@AydanPirani After you make appropriate changes to the validation webhook, you need to [build Katib Controller](https://github.com/kubeflow/katib/tree/master/cmd/katib-controller/v1beta1), and re-use this image in your deployment.
That should help you to test your code changes in the local Kind/Minikube cluster.

**Comment by AydanPirani** [comment]
@andreyvelich  Got it, thanks! Also, can you please point me to the docs page re. deployment? I'm looking at [this](https://www.kubeflow.org/docs/components/katib/getting-started/), but I don't see much about local Docker builds...

Thanks again for the help, I appreciate it!

**Comment by andreyvelich** [comment]
@AydanPirani You can find some info here: https://github.com/kubeflow/katib/blob/master/CONTRIBUTING.md#build-from-source-code, but we don't really explain how to update images.
You just need to take your local image and use it in the kustomize installs: https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/installs/katib-standalone/kustomization.yaml#L21-L23

After that, you can follow similar steps as for Training Operator to deploy Kind cluster locally and Katib using the standalone Kustomize overlay: https://github.com/kubeflow/training-operator/blob/master/CONTRIBUTING.md#run-a-kubernetes-cluster.

**Comment by AydanPirani** [comment]
Hi all, 

Still working on a repro from my end. 

@garymm  Does the following YAML file lead to the same error mentioned above? Just want to confirm that we both see the same thing!

```
---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: testveryveryverylargenamefillercharactersmorefillerspaces
spec:
  objective:
    type: minimize
    goal: 0.001
    objectiveMetricName: loss
  algorithm:
    algorithmName: random
  parallelTrialCount: 1
  maxTrialCount: 1
  maxFailedTrialCount: 1
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.01"
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/pytorch-mnist-cpu:latest
                command:
                  - "python3"
                  - "/opt/pytorch-mnist/mnist.py"
                  - "--epochs=1"
                  - "--batch-size=16"
                  - "--lr=${trialParameters.learningRate}"
                  - "--momentum=0.5"
                resources:
                  limits:
                    memory: "1Gi"
                    cpu: "0.5"
            restartPolicy: Never
```
