### ISSUE TITLE
vizier-db issue with readiness check

### ISSUE THREAD

**Issue by jax79sg** [kubeflow/katib#340]
I am currently experiencing an issue with vizier-db pod whereby the readiness probe failed. 

Is the database vizier supposed to be created when the pod is created or am I supposed to create it myself?

The following steps are my troubleshooting process:

Output from `kubectl describe pod -n kubeflow vizier-db-5b59cc744-nh8tp`:
```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  18m (x25 over 18m)  default-scheduler  persistentvolumeclaim "katib-mysql" is being deleted
  Normal   Pulled            18m                 kubelet, dh-ud     Container image "mysql:8.0.3" already present on machine
  Normal   Created           18m                 kubelet, dh-ud     Created container
  Normal   Started           18m                 kubelet, dh-ud     Started container
  Warning  Unhealthy         17m (x21 over 17m)  kubelet, dh-ud     Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
  Warning  Unhealthy  17m                 kubelet, dh-ud  Readiness probe errored: rpc error: code = Unknown desc = container not running (93f6c700f66ed68bbdaefb4be0a9843eebdcfbc66cf8ad832cc4cf002e8c279d)
  Warning  Unhealthy  3m (x425 over 17m)  kubelet, dh-ud  Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```
I have noticed that the readiness check for vizier-db pod is by using: 
`Readiness:      exec [/bin/bash -c mysql -D $$MYSQL_DATABASE -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'] delay=5s timeout=1s period=2s #success=1 #failure=3`

So I have tried to run a bash shell in the pod in order to execute the command: 
`mysql -D $$MYSQL_DATABASE -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
`
The output is:
```
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'dh'@'localhost' (using password: YES)
```
Then I tried to execute the command without password:
`mysql -D $$MYSQL_DATABASE -e 'SELECT 1'
`

The output is:
`ERROR 1049 (42000): Unknown database '159MYSQL_DATABASE'`

Then I tried to get the value of MYSQL_DATABASE using echo $MYSQL_DATABASE and the output is: vizier

So I tried to execute the command:
`mysql -D vizier -e 'SELECT 1'
`
The output is:
`ERROR 1049 (42000): Unknown database 'vizier'`
The only databases present in mysql are:
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
4 rows in set (0.00 sec)

```
and vizier is nowhere to be found.

**Comment by hougangliu** [comment]
the database vizier will be created automatically. Can you paste `kubectl logs -n kubeflow vizier-db-5b59cc744-nh8tp` here?

**Comment by jax79sg** [comment]
@hougangliu you are right! the vizier-core pod is not ready.
Here is the output from `kubectl describe pod vizier-core-6d65bc84c9-hrnnt -n kubeflow`:
```
Events:
  Type     Reason     Age                  From            Message
  ----     ------     ----                 ----            -------
  Warning  Unhealthy  15m (x102 over 90m)  kubelet, dh-ub  Readiness probe failed: timeout: failed to connect service ":6789" within 1s
  Warning  BackOff    52s (x331 over 87m)  kubelet, dh-ub  Back-off restarting failed container
```
I'm assuming if I manage to solve this issue, vizier-db pod would be working?

**Comment by hougangliu** [comment]
Yes, I think so. Maybe you can paste `kubectl -n kubeflow logs vizier-core-6d65bc84c9-hrnnt`

**Comment by hougangliu** [comment]
when vizier-core-6d65bc84c9-hrnnt  not ready, vizier-core service cannot be routed to an available pod.

I have no idea why vizier-core-6d65bc84c9-hrnnt log is empty. Do you do any change to  vizier-core deployment?

**Comment by jax79sg** [comment]
@hougangliu okay i ran `kubectl delete po vizier-core-6d65bc84c9-hrnnt -n kubeflow` and the problem still persists.

I suspect the problem lies with vizier-db not working which leads to vizier-core's issues.

**Comment by johnugeorge** [comment]
@jax79sg Can you try with higher initialDelaySeconds for vizier-db deployment? Currently, it is 5. Can you try changing to 15 and see if you still see the issue?

**Comment by johnugeorge** [comment]
@jax79sg you can make change in the https://github.com/kubeflow/kubeflow/blob/master/kubeflow/katib/vizier.libsonnet#L299 and redeploy.   

Also please post  output of `kubectl describe pod`  on vizier db pd?

**Comment by hougangliu** [comment]
maybe you can try to delete vizier-db and vizier-core pod at the same time to recovery

**Comment by jax79sg** [comment]
Update:
I managed to resolve the problem by changing vizier-db's deployment image from mysql:8.0.3 to mariadb.
Apparently when deploying using mysql:8.0.3, the environment variables declared is not being used at all and after changing to mariadb it is working fine.
Thanks for the help guys!

**Comment by johnugeorge** [comment]
@jax79sg Can you explain what you meant by "the environment variables declared is not being used at all"

**Comment by jax79sg** [comment]
@johnugeorge Hi, I am referring to the env under https://github.com/kubeflow/katib/blob/master/manifests/vizier/db/deployment.yaml,
```
spec:
      containers:
      - name: vizier-db
        image: mysql:8.0.3
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vizier-db-secrets
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "true"
          - name: MYSQL_DATABASE
            value: "vizier"
```
Strangely enough, even though the environment variables have been declared, it is not deployed with it. By changing the image from mysql:8.0.3 to mariadb, everything has been working fine so far.

**Comment by anilreddyv** [comment]
@jax79sg can you share your deployment file please? I am running exactly same issue as you described **"[Note] Access denied for user 'UNKNOWN_USER'@'localhost' (using password: YES)"** with mysql:8.0.3 version . If I try using mariadb it is failing with following error, not sure what version mariadb you have tried it thou?

2019-02-07  2:25:25 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-02-07  2:25:25 0 [ERROR] InnoDB: Invalid flags 0x4000 in ./ibdata1
2019-02-07  2:25:25 0 [ERROR] InnoDB: Plugin initialization aborted with error Data structure corruption
2019-02-07  2:25:26 0 [Note] InnoDB: Starting shutdown...

**Comment by bigdimple** [comment]
I am running exactly same issue too,but if I install kubeflow v0.3.0,everything has been working fine, vizier-db image is mysql:8.0.3 version too. if I install v0.4.0, vizier-db not working.

**Comment by emmayang** [comment]
Still seeing this issue in latest 0.5.1, and the odd thing is I found 

1. initially the `vizier` database is not there, so I created it by myself. 
2. then I called `mysql -D vizier -u root -e 'SELECT 1'` and it gave me output of:
```
root@vizier-db-6c5fcd5d4c-t4v2t:/# mysql -D vizier -u root -e 'SELECT 1'
+---+
| 1 |
+---+
| 1 |
+---+
```
while adding the password `-p $MY_PASS` in the command will shown and error like:
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

**Comment by emmayang** [comment]
Finally figured it out, and solved it by: 
1. manually create the `vizier` database if it's not there
2. add `user` and `--skip-name-resolve` option in startup args like below:

```
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vizier
        component: db
      name: vizier-db
    spec:
      containers:
      - args:
        - --datadir
        - /var/lib/mysql/datadir
        - -u
        - root
        - --skip-name-resolve
```

3. in readiness probe part, also add the `user` option, like below:
```
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mysql -D $$MYSQL_DATABASE -u root -e 'SELECT 1'
```

Hope this can help someone with similar issue.
