### ISSUE TITLE
Pass on resource limit/request

### ISSUE THREAD

**Issue by epa095** [kubeflow/katib#365]
I attempted to add resource limitation/request to the workerSpec by adding it to the spec.containers as show below, but this seems to be pruned somewhere on the way to k8s, because when I look at the generated jobs(and pods) they have empty resource limits/requests. 

This is a bit unfortunate, as these limits are good way to limit the load on the cluster.

```yaml
        spec:
          template:
            spec:
              containers:
              - name: {{.WorkerID}}
                image: myimg
                command:
                - "mystuff"
                - "--cv=3"
                {{- with .HyperParameters}}
                {{- range .}}
                - "{{.Name}}={{.Value}}"
                {{- end}}
                {{- end}}
              restartPolicy: Never
              resources:
                limits:
                  memory: 3G
                requests:
                  cpu: 1000m
```

**Comment by johnugeorge** [comment]
This is not expected. Did you verify the config of the generated workers?

**Comment by epa095** [comment]
I don't know exactly what you mean by that, but I have the following observations:
When I look at the studyjob by `kubectl  get studyjobs myjob -o yaml` the `resources` key is inside the `rawTemplate` with the correct values. When I look at a generated job by `kubectl  get jobs z7fa669d193714ea -o yaml` I see
under spec.template.spec.containers:
```yaml
...
        image: myimg
        imagePullPolicy: IfNotPresent
        name: z7fa669d193714ea
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
...
```
And this empty resources definition is then reflected in the pod as expected.
