### ISSUE TITLE
HELP WANTED: Starting Katib StudyJob

### ISSUE THREAD

**Issue by opus111** [kubeflow/katib#412]
Hello I am having trouble starting a StudyJob.  I think I am creating the Docker and YAML properly, and there are no complaints when it is created
```
$ kubectl create -f katib-test.yaml 
studyjob.kubeflow.org "katlib-pw6" created
```
However, the job does not appear in my Katib UI StudyJob List.  I am also not finding any associated logs or errors in the Kubernetes UI

How do I debug this?

Many thanks
P

**Comment by hougangliu** [comment]
please  share content of katib-test.yaml

**Comment by opus111** [comment]
Thanks.  Here you go
```
apiVersion: "kubeflow.org/v1alpha1"
kind: StudyJob
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: katib-pw6
spec:
  studyName: katib-pw6
  owner: crd
  optimizationtype: maximize
  objectivevaluename: y
  optimizationgoal: 1.0
  requestcount: 4
  metricsnames:
    - z
  parameterconfigs:
    - name: --x
      parametertype: double
      feasible:
        min: "-1.0"
        max: "1.0"
  workerSpec:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.WorkerID}}
            namespace: kubeflow
          spec:
            template:
              spec:
                containers:
                - name: {{.WorkerID}}
                  image: gcr.io/aml-dev/katib/katib-pw6:latest
                  command:
                  - "python"
                  - "katib-test.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  suggestionSpec:
    suggestionAlgorithm: "random"
    requestNumber: 3
```
And here is the trivial code I am running in my Docker
```
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--x",type=float,help="Input X tuning parameter")
args = parser.parse_args()
x = args.x
z = x+0.25
y = 1.0-(z*z)
print("z=%f" % z)
print("y=%f" % y)
```
And my Dockerfile
```
FROM python:3.6
MAINTAINER "Peter Wolf"

# show python logs as they occur
ENV PYTHONUNBUFFERED=0

# add project files
ADD *.py /home/
WORKDIR /home/
```
