### ISSUE TITLE
Docs about params of each suggestion algorithm

### ISSUE THREAD

**Issue by WestonLu** [kubeflow/katib#466]
Hi, may I ask if there were any docs about the suggestion algorithms? 
Especially the docs about params of each suggestion algorithm.

For example,  what does 'DefaultGrid 'and '--lr' mean in this example https://github.com/kubeflow/katib/blob/b25422ab1af0c5140013b325f2de7c9e3996fee0/examples/v1alpha1/grid-example.yaml ?

if '--lr' means the '--lr' param will be suggested with grid search, what will the other params be suggested, with random method? 

Thank you.

```
  parameterconfigs:
    - name: --lr
      parametertype: double
      feasible:
        min: "0.01"
        max: "0.03"
    - name: --num-layers
      parametertype: int
      feasible:
        min: "2"
        max: "5"
    - name: --optimizer
      parametertype: categorical
      feasible:
        list:
        - sgd
        - adam
        - ftrl
  workerSpec:
    goTemplate:
        templatePath: "cpuWorkerTemplate.yaml"
  suggestionSpec:
    suggestionAlgorithm: "grid"
    suggestionParameters:
      - 
          name: "DefaultGrid"
          value: "1"
      - 
          name: "--lr"
          value: "4"
```
