### ISSUE TITLE
Add make check to travis

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/katib#607]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

There are often some errors for `make check`, it is better to put the checking to CI.

Related issues for `make check` at https://github.com/kubeflow/katib/pull/606

/cc @hougangliu @gaocegege @richardsliu 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gyliu513** [comment]
@hougangliu not clear how to enable `make check` in katib prow at https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-presubmits.yaml#L82-L92 , do you have any comments for this?

```yaml
kubeflow/katib:
  - name: kubeflow-katib-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always
```
