### ISSUE TITLE
"Adding a template" usability issues

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#641]
1. The text box for the template name isn't clearly labelled. 

2. Attempting to save without entering a template name would close the window without any errors, so users have no idea if the template is actually created.

3. A lot of this should be auto-generated. For example, every Job (not counting TFJob or PytorchJob) contain these fields:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Trial}}
  namespace: {{.NameSpace}}
spec:
  template:
    spec:
      containers:
      - name: {{.Trial}}
      restartPolicy: Never
```

Only the image and command fields require customization.
