### ISSUE TITLE
Help Wanted: I want to run a tensorflow code.

### ISSUE THREAD

**Issue by warf34** [kubeflow/katib#666]
I am using katib on Linux.
This code works well on the docker. 
However, using katib does not work. 
I don't know why not
Please tell me how to fix it.

tensor_test.py
```
import argparse
import tensorflow as tf

parser = argparse.ArgumentParser()
parser.add_argument("--x",type=float,help="Input X tuning parameter")
args = parser.parse_args()

num = tf.constant(2.0*10)
sess = tf.Session()

x=args.x
y=x*2
z=x*x
a=sess.run(num)*x

print("x=%f" % x)
print("y=%f" % y)
print("z=%f" % z)
print("a=%f" % a)
```

tensor_test.yaml
```
apiVersion: "kubeflow.org/v1alpha1"
kind: StudyJob
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: tensor-test
spec:
  studyName: tensor-test
  owner: crd
  optimizationtype: maximize
  objectivevaluename: "a"
  optimizationgoal: 1.0
  requestcount: 3
  metricsnames:
    - "y"
    - "z"
  parameterconfigs:
    - name: --x
      parametertype: double
      feasible:
        min: "0.1"
        max: "0.9"
  workerSpec:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.WorkerID}}
            namespace: kubeflow
          spec:
            template:
              spec:
                containers:
                - name: {{.WorkerID}}
                  image: radics93/tensor_test:1.3
                  command:
                  - "python"
                  - "tensor_test.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  suggestionSpec:
    suggestionAlgorithm: "random"
    requestNumber: 3
```
Dockerfile
```
FROM python:3.6
FROM tensorflow/tensorflow
MAINTAINER "Lim"

ENV PYTHONUNBUFFERED=0

ADD . ./
WORKDIR ./
```

Running the Docker on my desktop
```
$ docker run radics93/tensor_test:1.3 python tensor_test.py --x=0.5
2019-06-19 17:57:06.148255: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3400025000 Hz
2019-06-19 17:57:06.148738: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4029110 executing computations on platform Host. Devices:
2019-06-19 17:57:06.148761: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
x=0.500000
y=1.000000
z=0.250000
a=10.000000
```
