### ISSUE TITLE
How to use suggestionAlgorithm as "hyperband" and what all suggestionParameters it has?

### ISSUE THREAD

**Issue by asispatra** [kubeflow/katib#677]

**Comment by johnugeorge** [comment]
See examples section: https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/hypb-example.yaml for v1alpha1 and  https://github.com/kubeflow/katib/blob/master/examples/v1alpha2/hyperband-example.yaml for v1alpha2

**Comment by asispatra** [comment]
Thanks for quick reply. I was looking this example: https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/hypb-example.yaml and got the following "suggestionParameters". Is there any other suggestionParameters parameters? and Where shall I get details about the suggestionParameters keys and values?
```
    suggestionParameters:
      - 
          name: "ResourceName"
          value: "--num-epochs"
      - 
          name: "eta"
          value: "3"
      -
          name: "r_l"
          value: "9"
```
