### ISSUE TITLE
How to get details about keys and values mentionrd in the examples .yaml file?

### ISSUE THREAD

**Issue by asispatra** [kubeflow/katib#678]
I was looking into the the Katib example provided in the github. But I did not get any details about the keys and values to specify. 

For example:
In this example https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/random-example.yaml, the following things are mentioned. So here what is `optimizationgoal`? Is there any suggestion parameters for `random` algorithm?
```
  optimizationtype: maximize
  objectivevaluename: Validation-accuracy
  optimizationgoal: 0.99
  requestcount: 4
  metricsnames:
- accuracy
...
  suggestionSpec:
    suggestionAlgorithm: "random"
requestNumber: 3
```

Thanks
