### ISSUE TITLE
katib metrics collector solution

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#685]
- [X] metricsCollector API #697
- [x] Pod level webhook for sidecar
- [ ] Job level webhook for sidecar (traced by #928)
- [x] StdOutCollector metricsCollector executor
- [x]	FileCollector metricsCollector executor
- [x] TfEventCollector metricsCollector executor
- [ ] PrometheusMetricCollector metricsCollector executor  **P2**  (traced by #929)

**Comment by hougangliu** [comment]
## Overview
This solution key ideas are:
1. Inject collector container as a sidecar into `Job`/`Tfjob`/`PytorchJob` Pod. Collector container collects metrics from worker container by parsing file or http based on metrics source, and persist metrics into persistent server, such as `katib-db` by `Katib-manager` or `metadata server`;
2. Introduce `TrialMetrics` CRD to trace metrics of trial by Kubernetes native way;
3. Introduce `Katib-Metrics-Manager` server to poll metrics of running Trial from metric persistent server and update related `TrialMetrics` CR. `Trial` controller updates trial's status based on coresponding `TrialMetrics` CR;

As for Early-Stop service (Maybe discuss it in other issue)
1. Early-Stop service will watch `Trial` metrics observation, once meeting goal, marks corresponding experiments as `Completed`.
1. Experiment controller will mark all running `Trial` as `Killed` or else if experiment `Completed`
1. Trial controller stops Job/TFJob/PytorchJob if `Trial` status is `Killed` or else 

See the architecture as below:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/10126721/61432863-4c185e80-a964-11e9-90da-f111316c0751.png">

## Data Structure
```
type ExperimentSpec struct {
	...
	MetricsCollectorSpec *MetricsCollectorSpec `json:"metricsCollectorSpec,omitempty"`
    ...
}

type MetricsCollectorSpec struct {
	Source    *SourceSpec    `json:"source,omitempty"`
	Collector *CollectorSpec `json:"collector,omitempty"`
}

type SourceSpec struct {
    // maybe model-train source code exposes metrics by http, such as HTTP endpoint in prometheus metric format
    HttpGet        *v1.HTTPGetAction `json:"httpGet,omitempty"`
    // during training model, metrics maybe be persistent into local file in source code, such as tfevent
    FileSystemPath *FileSystemPath   `json:"fileSystemPath,omitempty"`
}

type FileSystemKind string
const (
	DirectoryKind          FileSystemKind = "diretory"
	FileKind               FileSystemKind = "file"
)
type FileSystemPath struct {
    Path  string         `json:"path,omitempty"`
    Kind  FileSystemKind `json:"kind,omitempty"`
}

type CollectorKind string
const (
	StdOutCollector           CollectorKind = "stdOutCollector"
	FileCollector             CollectorKind = "fileCollector"
	TfEventCollector          CollectorKind = "tfEventCollector"
	PrometheusMetricCollector CollectorKind = "PrometheusMetricCollector"
	CustomCollector           CollectorKind = "customCollector"
	NoneCollector             CollectorKind = "noneCollector"
)

type CollectorSpec struct {
    Kind            CollectorKind `json:"kind"`
    CustomCollector *v1.Container `json:"customCollector,omitempty"`
}

type TrialMetrics struct {
    metav1.TypeMeta           `json:",inline"`
	metav1.ObjectMeta         `json:"metadata,omitempty"`
	Spec   TrialMetricsSpec   `json:"spec,omitempty"`
}

type TrialMetricsSpec struct {
    Observation *common.Observation `json:"observation,omitempty"`
}
```

1. For collector kind `StdOutCollector`, `FileCollector`, `TfEventCollector` and `PrometheusMetricCollector` (low priority), katib will maintain their collector implementations and build related images;`StdOutCollector`, `FileCollector` will be similar as current default metrics collector, and `TfEventCollector` keeps same as current tfevent metrics collector
2. katib will install a configmap `katib-config` to match images for each collector kind (not including customCollector), experiment controller will inject collecotr sidecar container into TrialTemplate (maybe it's better trial controller injects collecotr sidecar container into woker job)
3. Share metrics file/dir between worker container and collector container by [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)

## Example
1. For train source code prints metric in stdout, experiment should be like below (maybe if `metricsCollectorSpec` is nil, we can take it as this case by default):
```
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-experiment
spec:
  ...
  metricsCollectorSpec:
    collector:
      kind: stdOutCollector
  ...
```
2. For train source code prints metric into a specifed file with katib default format, experiment should be like below:
```
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-experiment
spec:
  ...
  metricsCollectorSpec:
    source:
      fileSystemPath:
        kind: file
        path: "/var/log/train.log"
    collector:
      kind: fileCollector
  ...
```
3. For train source code prints metric into a specifed file without katib default format, experiment should be like below (need user implements his custom collector):
```
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-experiment
spec:
  ...
  metricsCollectorSpec:
    source:
      fileSystemPath:
        kind: file
        path: "/var/log/train.log"
    collector:
      kind: customCollector
      customCollector:
        image: xx-repo/xx-user/user-custom-collector-image
        ...
  ...
```
4. For tensorflow source code persists metrics by tfevent:
```
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-experiment
spec:
  ...
  metricsCollectorSpec:
    source:
      fileSystemPath:
        kind: directory
        path: "/var/log/train/"
    collector:
      kind: tfEventCollector
```
5. For train source code persist its metrics into persistent server directory directly:
```
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-experiment
spec:
  ...
  metricsCollectorSpec:
    collector:
      kind: noneCollector
  ...
```
