### ISSUE TITLE
SuccessiveHalving and early-stopping not working for Katib Hyperband algorithm

### ISSUE THREAD

**Issue by asispatra** [kubeflow/katib#690]
SuccessiveHalving and early-stopping not working for Katib Hyperband algorithm. 
Any idea how to enable SuccessiveHalving and early-stopping features in Katib Hyperband algorithm?

Thanks.

**Comment by johnugeorge** [comment]
which katib version are you using?

**Comment by hougangliu** [comment]
@asispatra can you detail more about what you mean? saying what's your experiment yaml look like and so on.

**Comment by asispatra** [comment]
@hougangliu,

Hyperband related config in the yaml is as below:
```
  suggestionSpec:
    suggestionAlgorithm: "hyperband"
    suggestionParameters:
      - name: "ResourceName"
        value: "--max-epoch"
      - name: "eta"
        value: "3"
      - name: "r_l"
        value: "9"
```
This launches 9 jobs together at the first time. Once these all are completed, the experiment status is completed. Currently I am not seeing anything related to SuccessiveHalving and early-stopping.

Lets say my each Deep-learning job will run for 10 epochs which requires 1 GPU and I have 8 GPUs in total. For hyper-parameter optimization, First time I want to launch 8 parallel jobs and later based on the feedback let the Hyperband algo decide how may job it need to run next and let the algo decide it should do early stopping or not. 

For these scenario what should be the Hyparband configuration in the yaml file?

Thanks.
