### ISSUE TITLE
How to use tensorflow-gpu?

### ISSUE THREAD

**Issue by warf34** [kubeflow/katib#705]
I would like to use katib in Minikube with tensorflow-gpu.
I downloaded katib [here](https://github.com/kubeflow/katib) and run this [deploy.sh](https://github.com/kubeflow/katib/blob/master/examples/v1alpha2/MinikubeDemo/deploy.sh)
it works well In docker, but does not work in katib
how to use katib with tensorflow-gpu?
Do I need to install additional?

below are my files

Dockerfile
```
FROM python:3.7

RUN pip3 install tensorflow-gpu

ADD * ./
WORKDIR ./
```

mnist.py
```
import tensorflow as tf
import argparse
import time

from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

parser = argparse.ArgumentParser()
parser.add_argument("--lr",type=float,help="Input")
args = parser.parse_args()

start = time.time()
# parameters
learning_rate = args.lr
training_epochs = 10
batch_size = 100

# input place holders
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])

# weights & bias for nn layers
W1 = tf.get_variable("W1", shape=[784, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b1 = tf.Variable(tf.random_normal([512]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.get_variable("W2", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b2 = tf.Variable(tf.random_normal([512]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)

W3 = tf.get_variable("W3", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b3 = tf.Variable(tf.random_normal([512]))
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)

W4 = tf.get_variable("W4", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b4 = tf.Variable(tf.random_normal([512]))
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)

W5 = tf.get_variable("W5", shape=[512, 10],
                     initializer=tf.contrib.layers.xavier_initializer())
b5 = tf.Variable(tf.random_normal([10]))
hypothesis = tf.matmul(L4, W5) + b5

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(
    logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(mnist.train.num_examples / batch_size)

    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        feed_dict = {X: batch_xs, Y: batch_ys}
        c, _ = sess.run([cost, optimizer], feed_dict=feed_dict)
        avg_cost += c / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning Finished!')

# Test model and check accuracy
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
acc = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
accuracy = sess.run(acc, feed_dict={X: mnist.test.images, Y: mnist.test.labels})
print('accuracy=%f' % accuracy)
end = time.time()
result_time = end - start
print(result_time)
```

random.yaml
```
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-mnist-gpu
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: "accuracy"
    additionalMetricNames:
  algorithm:
    algorithmName: random
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: warf34/mnist-gpu:latest
                  command:
                  - "python3"
                  - "mnist.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.001"
        max: "0.003"
```

**Comment by gaocegege** [comment]
You need to define resources in rawTemplate to require GPUs for the container.

**Comment by warf34** [comment]
> You need to define resources in rawTemplate to require GPUs for the container.

I saw nasjob-example-RL.yaml and changed the container as shown below.
But it does not work. Is this wrong?
```
              spec:
                containers:
                - name: {{.Trial}}
                  image: warf34/mnist-gpu:latest
                  command:
                  - "python3"
                  - "mnist.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                  resources:
                    limits:
                      nvidia.com/gpu: 1
                restartPolicy: Never
```
