### ISSUE TITLE
Help wanted! Does not show UI and Experiment is not completed continuously.

### ISSUE THREAD

**Issue by warf34** [kubeflow/katib#712]
i would like to run tensorflow-gpu in Minikube like [this](https://github.com/kubeflow/katib/issues/705) but it does not working!

so, i try to run tensorflow by only cpu.
however, it did not working too...

my code
```
import tensorflow as tf
import argparse
import time

from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

parser = argparse.ArgumentParser()
parser.add_argument("--lr",type=float,help="Input")
args = parser.parse_args()

start = time.time()
# parameters
learning_rate = args.lr
training_epochs = 20
batch_size = 100

# input place holders
X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])

# weights & bias for nn layers
W1 = tf.get_variable("W1", shape=[784, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b1 = tf.Variable(tf.random_normal([512]))
L1 = tf.nn.relu(tf.matmul(X, W1) + b1)

W2 = tf.get_variable("W2", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b2 = tf.Variable(tf.random_normal([512]))
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)

W3 = tf.get_variable("W3", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b3 = tf.Variable(tf.random_normal([512]))
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)

W4 = tf.get_variable("W4", shape=[512, 512],
                     initializer=tf.contrib.layers.xavier_initializer())
b4 = tf.Variable(tf.random_normal([512]))
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)

W5 = tf.get_variable("W5", shape=[512, 10],
                     initializer=tf.contrib.layers.xavier_initializer())
b5 = tf.Variable(tf.random_normal([10]))
hypothesis = tf.matmul(L4, W5) + b5

# define cost/loss & optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(
    logits=hypothesis, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

# initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(mnist.train.num_examples / batch_size)

    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        feed_dict = {X: batch_xs, Y: batch_ys}
        c, _ = sess.run([cost, optimizer], feed_dict=feed_dict)
        avg_cost += c / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning Finished!')

# Test model and check accuracy
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y, 1))
acc = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
accuracy = sess.run(acc, feed_dict={X: mnist.test.images, Y: mnist.test.labels})
print('accuracy:', accuracy)
end = time.time()
result_time = end - start
print(result_time)
```

random.yaml
```
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-mnist-cpu
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: "accuracy"
    additionalMetricNames:
  algorithm:
    algorithmName: random
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: warf34/mnist-cpu:latest
                  command:
                  - "python3"
                  - "mnist.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.001"
        max: "0.003"
```
if i enter this command `kubectl get trials -n kubeflow`,
result is
```
NAME                        STATUS    AGE
random-mnist-cpu-thmd6lbm   Running   38m
random-mnist-cpu-wndvmpf4   Running   38m
random-mnist-cpu-xct87b84   Running   38m
```
but i enter this command `kubectl -n kubeflow get pods`, result is
```
NAME                                                    READY   STATUS      RESTARTS   AGE
katib-controller-7f985d6cd6-mv8rs                       1/1     Running     0          40m
katib-db-b48df7777-2l2pk                                1/1     Running     0          40m
katib-manager-7946dd5984-fdzrg                          1/1     Running     0          40m
katib-manager-rest-647f694b7d-4gxtt                     1/1     Running     0          40m
katib-suggestion-bayesianoptimization-94c87dd64-gszb8   1/1     Running     0          40m
katib-suggestion-grid-58d9dfb5fd-cqmn2                  1/1     Running     0          40m
katib-suggestion-hyperband-778bb768c8-rrnss             1/1     Running     0          40m
katib-suggestion-nasrl-d84fbb8f4-djg2j                  1/1     Running     0          40m
katib-suggestion-random-7f96c4d77b-fp7pf                1/1     Running     0          40m
katib-ui-6cf97db464-7vf2v                               1/1     Running     0          40m
random-mnist-cpu-thmd6lbm-pd4nj                         0/1     Completed   0          38m
random-mnist-cpu-wndvmpf4-8ztrq                         0/1     Completed   0          38m
random-mnist-cpu-xct87b84-2gxls                         0/1     Completed   0          38m
```

and enter this command `kubectl describe pod random-mnist-cpu-thmd6lbm-pd4nj -n kubeflow` result is below
```
Name:           random-mnist-cpu-thmd6lbm-pd4nj
Namespace:      kubeflow
Priority:       0
Node:           minikube/10.0.2.15
Start Time:     Mon, 05 Aug 2019 16:30:47 +0900
Labels:         controller-uid=56de3bce-1bcb-42df-bb3e-ce97dea9f73a
                job-name=random-mnist-cpu-thmd6lbm
Annotations:    <none>
Status:         Succeeded
IP:             172.17.0.16
Controlled By:  Job/random-mnist-cpu-thmd6lbm
Containers:
  random-mnist-cpu-thmd6lbm:
    Container ID:  docker://eb7b29e3d315b4a021bd7cc1d142558f9b4d6f1ce7898b9742dcbe34a5c138b1
    Image:         warf34/mnist-cpu:latest
    Image ID:      docker-pullable://warf34/mnist-cpu@sha256:e35e9c0794fa8b672ca3bfa0941e2945ad34619b5d5197ce32242c0b4bdd9119
    Port:          <none>
    Host Port:     <none>
    Command:
      python3
      mnist.py
      --lr=0.002564224564690085
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 05 Aug 2019 16:31:09 +0900
      Finished:     Mon, 05 Aug 2019 16:35:57 +0900
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-v8hb7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-v8hb7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-v8hb7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  38m   default-scheduler  Successfully assigned kubeflow/random-mnist-cpu-thmd6lbm-pd4nj to minikube
  Normal  Pulling    38m   kubelet, minikube  Pulling image "warf34/mnist-cpu:latest"
  Normal  Pulled     37m   kubelet, minikube  Successfully pulled image "warf34/mnist-cpu:latest"
  Normal  Created    37m   kubelet, minikube  Created container random-mnist-cpu-thmd6lbm
  Normal  Started    37m   kubelet, minikube  Started container random-mnist-cpu-thmd6lbm
```

other experiment is not start and UI(http://127.0.0.1:8000/katib/#/katib/hp_monitor/random-mnist-cpu) is not showed anything

how to test my code in 'minikube'?
or my code is wrong?

and if you don't mind, can you tell me how to use tensorflow-gpu in my [issue?](https://github.com/kubeflow/katib/issues/705)
