### ISSUE TITLE
Katib-db stuck at login as root

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/katib#725]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I try to deploy Katib on IBM Cloud and use IBM Cloud NFS storage as the persistent volume. However, the Katib-db always stuck at 
```
2019-08-15T17:57:04.708439Z 35240 [Note] Access denied for user 'root'@'localhost' (using password: YES)
2019-08-15T17:57:06.771754Z 35241 [Note] Access denied for user 'root'@'localhost' (using password: YES)
2019-08-15T17:57:08.713518Z 35242 [Note] Access denied for user 'root'@'localhost' (using password: YES)
```

One thing I do realize is our persistent storage doesn't allow nonroot user to write files. Although the deployment is working if we try to use hostpath, it won't be persistent and resilient in our use case. 

We also try our storage with the KubeFlow Pipeline MySQL and it works fine there. The only different is KubeFlow Pipeline doesn't have any password for its MySQL instance. 

**What did you expect to happen:**
Katib-db should be deployed and login as root.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 0.5.1 and 0.6.0
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.14.5
- OS (e.g. from `/etc/os-release`): ubuntu 16

**Comment by gaocegege** [comment]
Can you remove the pwd in the katib-db then have another try?

**Comment by hougangliu** [comment]
@Tomcli you can try solution 1): add "runAsUser: 0" in katib-db deployment as below; 2) add "no_root_squash" in nfs share dir
```
    spec:
      containers:
      - name: katib-db
        image: mysql:8.0.3
        securityContext:
          runAsUser: 0
        args:
        - --datadir
        - /var/lib/mysql/datadir
```
