### ISSUE TITLE
Experiment and trial are not failing if its corresponding job fails

### ISSUE THREAD

**Issue by md-shabbir** [kubeflow/katib#759]
/kind bug

**What steps did you take and what happened:**

- Installed kubeflow 0.6.2 using kfctl [https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/)
- Tried this example [https://github.com/kubeflow/katib#running-examples](https://github.com/kubeflow/katib#running-examples) (v1alpha2) with few modification. Changed few field values(parallelTrialCount, maxTrialCount, maxFailedTrialCount) and changed the tfjob container command to make it fail.
- Modified experiment manifest:
```yaml
apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: tfjob-example
spec:
  parallelTrialCount: 1
  maxTrialCount: 3
  maxFailedTrialCount: 1
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy_1
  algorithm:
    algorithmName: random
  parameters:
    - name: --learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: --batch_size
      parameterType: int
      feasibleSpace:
        min: "100"
        max: "200"
  trialTemplate:
    retain: false
    goTemplate:
        rawTemplate: |-
          apiVersion: "kubeflow.org/v1"
          kind: TFJob
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
           tfReplicaSpecs:
            Worker:
              replicas: 1 
              restartPolicy: Never
              template:
                spec:
                  containers:
                    - name: tensorflow 
                      image: gcr.io/kubeflow-ci/tf-mnist-with-summaries:1.0
                      imagePullPolicy: Always
                      command:
                        - "python-error-it"
                        - "/var/tf_mnist/mnist_with_summaries.py"
                        - "--log_dir=/train/{{.Trial}}"
                        {{- with .HyperParameters}}
                        {{- range .}}
                        - "{{.Name}}={{.Value}}"
                        {{- end}}
                        {{- end}}
                      volumeMounts:
                        - mountPath: "/train"
                          name: "train"
                  volumes:
                    - name: "train"
                      persistentVolumeClaim:
                        claimName: "tfevent-volume"
  metricsCollectorSpec:
    goTemplate:
      rawTemplate: |-
        apiVersion: batch/v1beta1
        kind: CronJob
        metadata:
          name: {{.Trial}}
          namespace: {{.NameSpace}}
        spec:
          schedule: "*/1 * * * *"
          successfulJobsHistoryLimit: 0
          failedJobsHistoryLimit: 1
          jobTemplate:
            spec:
              template:
                spec:
                  containers:
                  - name: {{.Trial}}
                    image: gcr.io/kubeflow-images-public/katib/v1alpha2/tfevent-metrics-collector
                    args:
                    - "python"
                    - "main.py"
                    - "-t"
                    - "{{.Trial}}"
                    - "-d"
                    - "/train/{{.Trial}}"
                    - "-m"
                    - "accuracy_1"
                    volumeMounts:
                        - mountPath: "/train"
                          name: "train"
                  volumes:
                    - name: "train"
                      persistentVolumeClaim:
                          claimName: "tfevent-volume"
                  restartPolicy: Never
                  serviceAccountName: metrics-collector
```
Few relevant outputs:
```
shabbir:~$ kubectl get tfjob -n kubeflow
NAME                     STATE    AGE
tfjob-example-k77m5cws   Failed   21m
shabbir:~$ kubectl get trial -n kubeflow
NAME                     STATUS    AGE
tfjob-example-k77m5cws   Running   24m
shabbir:~$ kubectl get experiment -n kubeflow
NAME            STATUS    AGE
tfjob-example   Running   24m
```
Here we see corresponding job failed but trial and experiment are still running.
 
**What did you expect to happen:**
Trial should fail and then ultimately experiment should fail.

**Environment:**

- Kubeflow version:
```
0.6.2
```
- Kubernetes version: (use `kubectl version`):
```
shabbir:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from `/etc/os-release`):
```
shabbir:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
