### ISSUE TITLE
How can we wget $IP-of-katib-ui directly?

### ISSUE THREAD

**Issue by b675987273** [kubeflow/katib#995]
/kind feature

**Describe the solution you'd like**
[I would like to wget a ui-web by using katib-ui service. A full kubeflow is too big]

**Anything else you would like to add:**
[Or, you can tell us how it works]

**Comment by gaocegege** [comment]
You can make the katib-ui service to be a node-port service. Then you can visit it directly.

**Comment by b675987273** [comment]
I changed the svc model and try to curl ip:nodeport. But it is still "404 page not found"
```yaml
katib-ui-svc.yaml
....
spec:
  clusterIP: 10.233.63.40
  externalTrafficPolicy: Cluster
  ports:
  - name: ui
    nodePort: 32501
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: katib
    app.kubernetes.io/component: katib
    app.kubernetes.io/instance: katib-controller-v0.7.1
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: katib-controller
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.7.1
    component: ui
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
```shell
katib-controller-57fb4644cd-bd8l8                              1/1     Running             1          126m
katib-db-7d874dbf97-6245t                                      1/1     Running             0          75m
katib-manager-67cd69b7f9-59tjd                                 1/1     Running             11         129m
katib-ui-7cc7bfb97d-qrhbl                                      1/1     Running             0          131m
```
